### ISSUE TITLE
Media keys don't work until about 15 minutes after login

### ISSUE THREAD

**Issue by jtrees** [linuxmint/cinnamon-settings-daemon#102]
When I log in my media keys do not work. I can press them and the input is queued but the actions only get performed much, much later (like 15 minutes after login). After this initial phase everything works as it should.

My guess is that perhaps some other plugin is having issues and blocking the initialisation of "media-keys" which (according to dconf) has a priority of 97.

I have no idea what kind of information to provide to be useful here though. Is there perhaps a settings-daemon log?

**Comment by talamus** [comment]
@jtrees, if you run [iotop](https://linux.die.net/man/1/iotop), you probably will see cinnamon-settings-daemon eating 99% of your disk I/O. I have no idea why it is doing that. Re-installing does not help.

When the disk I/O finishes the media keys begins to function normally.

I have an encrypted home partition. Could that have something to do with this?
Also, we need better logging / stats viewing for cinnamon-settings-daemon.

**Comment by jtrees** [comment]
Wow, it's been a while and I guess this is still an issue. I have switched distros since ([elementary OS](https://elementary.io/) ftw) so I cannot verify what you mentioned but thanks for the info. Here's hoping this gets picked up by someone soon.

**Comment by icarter09** [comment]
@talamus are you still experiencing this issue?

**Comment by talamus** [comment]
Sorry, I am not using Linux Mint anymore.
