### ISSUE TITLE
Cinnamon Settings Daemon crashes on login with NVIDIA drivers  Ignore X errors when applying xrandr configuration (fixes CSD crashe useless

### ISSUE THREAD

**Issue by baohuams** [linuxmint/cinnamon-settings-daemon#105]
this is package:
ii  cinnamon-settings-daemon                         2.2.4+qiana-1cdos1.6ubuntu1                            amd64        daemon handling the Cinnamon session settings
nfs@nfs-Lenovo-Product:~$ dpkg -l | grep cinnamon-desktop
ii  cinnamon-desktop-data                            2.8.0-2ubuntu1                                         all          Common files for Cinnamon desktop apps
ii  libcinnamon-desktop0                             2.2.3+qiana                                         amd64        Utility library for loading .desktop files - runtime files
ii  libcinnamon-desktop4:amd64                       2.8.0-2ubuntu1                                         amd64        Cinnamon library for loading .desktop files

the xsession-error 
(cinnamon-settings-daemon:21587): Gdk-ERROR **: The program 'cinnamon-settings-daemon' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 11910 error_code 3 request_code 18 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
    JS ERROR: !!!   Exception was: Error: Expected type utf8 for Argument 'format' but got type 'undefined' (nil) 
    JS ERROR: !!!     message = '"Expected type utf8 for Argument 'format' but got type 'undefined' (nil)"'
    JS ERROR: !!!     fileName = '"/usr/share/cinnamon/js/ui/environment.js"'
    JS ERROR: !!!     lineNumber = '75'

the lspci message
01:00.0 VGA compatible controller: NVIDIA Corporation Device 104c (rev a1)

**Comment by baohuams** [comment]
Dec 10 13:48:03 nfs-Lenovo-Product acpid: client connected from 20786[0:0]
Dec 10 13:48:03 nfs-Lenovo-Product acpid: 1 client rule loaded
Dec 10 13:48:03 nfs-Lenovo-Product anacron[31555]: Anacron 2.3 started on 2015-12-10
Dec 10 13:48:03 nfs-Lenovo-Product anacron[31555]: Normal exit (0 jobs run)
Dec 10 13:48:03 nfs-Lenovo-Product anacron[31614]: Anacron 2.3 started on 2015-12-10
Dec 10 13:48:03 nfs-Lenovo-Product anacron[31614]: Normal exit (0 jobs run)
Dec 10 13:48:04 nfs-Lenovo-Product kernel: [ 9674.542413] traps: cinnamon-settin[21587] trap int3 ip:7f412f64ac13 sp:7ffd0ca6c910 error:0
Dec 10 13:48:05 nfs-Lenovo-Product NetworkManager[888]: <info> (eth0): carrier now ON (device state 70)
Dec 10 13:48:05 nfs-Lenovo-Product kernel: [ 9675.907694] r8169 0000:02:00.0 eth0: link up
Dec 10 13:48:06 nfs-Lenovo-Product dhclient: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 12 (xid=0x3f61efc5)
Dec 10 13:48:09 nfs-Lenovo-Product colord: device removed: xrandr-Dell Inc.-DELL E178FP-U045K93P2VJL
Dec 10 13:48:09 nfs-Lenovo-Product colord: Profile removed: icc-8b3492b46731a95f8b5fc3ed97b796bc
Dec 10 10:43:49 nfs-Lenovo-Product x-session-manager[21494]: Gtk-WARNING: Theme parsing error: gtk-widgets.css:73:22: '' is not a valid color name
Dec 10 13:48:09 nfs-Lenovo-Product x-session-manager[21494]: WARNING: Application 'cinnamon-settings-daemon.desktop' killed by signal 5
Dec 10 13:48:10 nfs-Lenovo-Product dbus[823]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Dec 10 13:48:11 nfs-Lenovo-Product dbus[823]: [system] Successfully activated service 'org.freedesktop.systemd1'
Dec 10 13:48:12 nfs-Lenovo-Product colord: Device added: xrandr-Dell Inc.-DELL E178FP-U045K93P2VJL
Dec 10 13:48:12 nfs-Lenovo-Product x-session-manager[21494]: Gtk-WARNING: Theme parsing error: gtk-widgets.css:73:22: '' is not a valid color name
Dec 10 13:48:13 nfs-Lenovo-Product colord: Profile added: icc-8b3492b46731a95f8b5fc3ed97b796bc
Dec 10 13:48:16 nfs-Lenovo-Product NetworkManager[888]: <info> (eth0): IP6 addrconf timed out or failed.
Dec 10 13:48:16 nfs-Lenovo-Product NetworkManager[888]: <info> Activation (eth0) Stage 4 of 5 (IPv6 Configure Timeout) scheduled...
Dec 10 13:48:16 nfs-Lenovo-Product NetworkManager[888]: <info> Activation (eth0) Stage 4 of 5 (IPv6 Configure Timeout) started...
Dec 10 13:48:16 nfs-Lenovo-Product NetworkManager[888]: <info> Activation (eth0) Stage 4 of 5 (IPv6 Configure Timeout) complete.
Dec 10 13:48:18 nfs-Lenovo-Product dhclient: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 12 (xid=0x3f61efc5)
Dec 10 13:48:30 nfs-Lenovo-Product dhclient: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 17 (xid=0x3f61efc5)
Dec 10 13:48:30 nfs-Lenovo-Product cinnamon-screensaver-dialog: pam_ecryptfs: seteuid error 
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <warn> (eth0): DHCPv4 request timed out.
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <info> (eth0): canceled DHCP transaction, DHCP client pid 31151 
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <info> Activation (eth0) Stage 4 of 5 (IPv4 Configure Timeout) scheduled...
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <info> Activation (eth0) Stage 4 of 5 (IPv4 Configure Timeout) started...
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <info> (eth0): device state change: ip-config -> failed (reason 'ip-config-unavailable') [70 120 5]
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <info> NetworkManager state is now DISCONNECTED
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <warn> Activation (eth0) failed for connection 'Wired connection 1'
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <info> Activation (eth0) Stage 4 of 5 (IPv4 Configure Timeout) complete.
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <info> (eth0): device state change: failed -> disconnected (reason 'none') [120 30 0] 
Dec 10 13:48:41 nfs-Lenovo-Product NetworkManager[888]: <info> (eth0): deactivating device (reason 'none') [0]
Dec 10 13:48:44 nfs-Lenovo-Product NetworkManager[888]: <info> Auto-activating connection 'Wired connection 1'.

**Comment by baohuams** [comment]
nfs@nfs-Lenovo-Product:/var/crash/a$ gdb cinnamon-settings-daemon  CoreDump 
GNU gdb (Ubuntu 7.7-0ubuntu3) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cinnamon-settings-daemon...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 21587]
[New LWP 21597]
[New LWP 21803]
[New LWP 21841]
[New LWP 21594]
[New LWP 31156]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/cinnamon-settings-daemon/cinnamon-settings-daemon'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f412f64ac13 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007f412f64ac13 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f412f64ad72 in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f412e578351 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007f412e580ab1 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x00007f412eb1c54b in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007f412eb195e7 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007f412eb19695 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f412eb1a578 in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f412dbf2a74 in XSyncQueryCounter () from /usr/lib/x86_64-linux-gnu/libXext.so.6
#9  0x00007f4116aea4a9 in gpm_idletime_get_time () from /usr/lib/cinnamon-settings-daemon-3.0/libpower.so
#10 0x00007f4116aefb99 in ?? () from /usr/lib/cinnamon-settings-daemon-3.0/libpower.so
#11 0x00007f4116aefe50 in ?? () from /usr/lib/cinnamon-settings-daemon-3.0/libpower.so
#12 0x00007f412bc4badc in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#13 0x00007f412bc4b40c in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#14 0x00007f412f913bf8 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f412f9133b8 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f412f924d3d in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007f412f92ca29 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007f412f92cce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007f412fc272ec in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#20 0x00007f412fc176c5 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#21 0x00007f412f643ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f412f644048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f412f64430a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f413026ffe5 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x0000000000403885 in main ()
(gdb)

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue.
