### ISSUE TITLE
Select different wallpapers for multiple monitors

### ISSUE THREAD

**Issue by lehitoskin** [linuxmint/cinnamon-settings-daemon#108]
I have a two-monitor setup and currently the Backgrounds selection thing will only select backgrounds for both of the monitors. This is less than ideal because one monitor is 1920x1080 and the other is 1280x1024 - a wallpaper that will work for one monitor will most likely not work for the other.

Currently I use `feh` to set my individual wallpapers, but it would be so much nicer to have this done natively through Cinnamon.

**Comment by leigh123linux** [comment]
'cinnamon-settings backgrounds' is part of cinnamon so please file your issue there instead.

https://github.com/linuxmint/Cinnamon/issues

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/2301
