### ISSUE TITLE
Power widget no longer auto-updates

### ISSUE THREAD

**Issue by jakebailey** [linuxmint/cinnamon-settings-daemon#111]
I'm on Arch Linux, and some recent update (within the past two days) has made the power widget not update automatically. If I run `upower -d` in a terminal, the widget does update to the correct percentage and time estimate.

Looking over what was updated, I believe that it is dbus-glib, which moved from version 0.104 to 0.106, and I think that it's used by the widget.

Rebuilding the settings daemon doesn't solve the issue at least, so there's something else going on.

**Comment by jakebailey** [comment]
I just downgraded, and it doesn't actually help. I'll try to look to see what else it could be, but I think you guys have other issues on your mind...

**Comment by alium** [comment]
@jakebailey: problem ist mayby with upower-0.99.4 - after downgrading power widget works again.
Maybe because daemon: port main() to GDBus??

**Comment by alium** [comment]
arch develop said: 
So far I don't see any issue with upower 0.99.4-2 in GNOME, so this looks like a cinnamon issue.

**Comment by jakebailey** [comment]
Yup, 0.99.3 works. I only downgraded to the previous build of 0.99.4, which wasn't far enough. I guess I'll hold the package back until something changes (we'll see if I have time to look into this myself).

**Comment by alium** [comment]
fixed in 2.8.4 via https://github.com/linuxmint/cinnamon-settings-daemon/issues/113

Thanks!

**Comment by jakebailey** [comment]
Any idea as to when this is going to make it into a versioned release? I can build from source, but it'd be cool to get this into the Arch repos eventually to get all of the "normal" users fixed officially.

**Comment by alium** [comment]
@jakebailey: in Arch Linux is already fixed - cinnamon-settings-daemon-2.8.4-2 (https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/cinnamon-settings-daemon&id=b4508211fcb5808dc633d242419b26c94a29fb3f). I do not have any more problems, everything works. 

Just install upower 0.99.4 and cinnamon-settings-daemon-2.8.4-2,  "sudo systemctl daemon-reload" and restart cinnamon.

**Comment by jakebailey** [comment]
Great, thanks. I've been watching the package, but I guess I missed that they added a patch. (I've been holding upower back in the meantime.)

**Comment by alium** [comment]
this bug can be closed :-)
