### ISSUE TITLE
Cinnamon-settings-daemon Severe Crash

### ISSUE THREAD

**Issue by borhansci** [linuxmint/cinnamon-settings-daemon#134]
Cinnamon-settings-daemon keep crashing in my Linux Mint 18 to the point that everything is completely freeze and I am unable to touch anything, even opening the terminal. Crashes are random and not related to a specific event.

Here is my hardware info:

https://gist.github.com/borhansci/9b9e03c877c65b13fc15e8aec13500de

And the contents of ".xsession-errors" file:

https://gist.github.com/borhansci/5192d0483c518f0af3d1881fb751a30d

**Comment by JosephMcc** [comment]
You don't need to report this twice https://github.com/linuxmint/Cinnamon/issues/5752
