### ISSUE TITLE
cinnamon-settings-daemon 3.2.0 Memory Leak with VMware Workstation 12

### ISSUE THREAD

**Issue by borhansci** [linuxmint/cinnamon-settings-daemon#139]
Whenever I startup a VM machine with VMware Workstation 12, cinnamon-settings-daemon starts to fill up the memory till Cinnamon crashes

**Comment by kost757** [comment]
In installed on the real machine in my computer too, so: https://github.com/linuxmint/cinnamon-settings-daemon/issues/144

**Comment by sanyikaz** [comment]
I got the same issue, cinnamon-settings-deamon takes up to 7Gig of RAM while running a VMWare Machine. Even after shutting down the machine, the memory consumption still stays extremely high.

![bildschirmfoto vom 2017-06-06 22-09-07](https://user-images.githubusercontent.com/29246846/26866088-efda3530-4b5f-11e7-8e27-2370f7febbcd.png)

**Comment by borhansci** [comment]
Update to Cinnamon 3.4.1 with cinnamon-settings-daemon 3.4.1, It will fix the issue

**Comment by sanyikaz** [comment]
Sorry for late answer, but updating to 3.4.1 helped out with this issue. 
But virtual machines (e.g. Windows 7 VirtualBox with 4096MB RAM) does still take up to 7Gig... Guess this is not a cinnamon-related issue, btrfs instead.
