### ISSUE TITLE
Add flat pointer profile tick to options please

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/cinnamon-settings-daemon#140]
Reopening https://github.com/linuxmint/cinnamon-desktop/issues/60

Since libinput 1.1 the developers added flat profile. It gives 1:1 mouse movement, i.e. without any acceleration (handy for gamers). You are able to adjust only speed of pointer with this profile
Desripton on the bottom of the page: http://wayland.freedesktop.org/libinput/doc/latest/pointer-acceleration.html

**Comment by icarter09** [comment]
@Yanpas  are you still experiencing this issue?

**Comment by Yanpas** [comment]
No, not using mint now

**Comment by icarter09** [comment]
@Yanpas no worries and thanks for the update.
