### ISSUE TITLE
Make volume step adjustable

### ISSUE THREAD

**Issue by MichaelLawton** [linuxmint/cinnamon-settings-daemon#143]
There is a patch here which should work with without changing much:
https://bugs.launchpad.net/ubuntu/+source/gnome-settings-daemon/+bug/871133/comments/37

Ref:
https://askubuntu.com/questions/10525/how-can-i-make-the-volume-change-in-smaller-increments/704733#704733
https://bugs.launchpad.net/ubuntu/+source/gnome-settings-daemon/+bug/871133

**Comment by deskwizard** [comment]
Here are the 3 required commits for 19.2. 

I would like some feedback.
This is my first time doing that sort of things, so please bare with me.

Change to schema to add required key. 
[url]https://github.com/deskwizard/cinnamon-desktop/commit/53658157be1cb82b91df4a55e82802ac1bf228a9[/url]

Seemed like the most appropriate place to put that key, does it make sense?


Changes to the sound applet to match (Required).
[url]https://github.com/deskwizard/cinnamon/commit/d52db3b2cec740939467d8fa7b49c4605896e036[/url]

Requires applet restart to apply the new setting, is that okay or should I look for another way?


Modification to csd-mediakeys
[url]https://github.com/deskwizard/cinnamon-settings-daemon/commit/1362d19eaeaf91f735d158a6f1db27862229e951[/url]

I am not quite sure what's the procedure (if any) going forward, please let me know if you can, I'll do my best to be helpful.

Thanks,
deskwizard

**Comment by icarter09** [comment]
@MichaelLawton  are you still experiencing this issue?

**Comment by Corax26** [comment]
@icarter09 Yes the issue is still there. I have my own build of settings-daemon with a custom value for `VOLUME_STEP` in `plugins/media-keys/csd-media-keys-manager.c`. It would be really helpful to have a runtime setting for it.

**Comment by thomasjahoda** [comment]
@icarter09 can we revive this issue? why is it still labeled as "Gathering Info"?

**Comment by Loufute** [comment]
@icarter09 > Having the ability to change volume step (at least in a config file, but preferably in [sound?] preferences) would be awesome indeed. Several people already asked for that, for instance on Linux Mint Forums ([#1](https://forums.linuxmint.com/viewtopic.php?t=312162) with a workaround by recompiling, [#2](https://forums.linuxmint.com/viewtopic.php?f=29&t=347770&p=2005631), [#3](https://forums.linuxmint.com/viewtopic.php?t=215772&p=1672717#p1672717)...).
[I hope I am doing this right, not very familiar with GitHub...yet]

**Comment by whinis** [comment]
Can confirm, just got here after going to the Linux Mint Forums. Seems like a regression as the old plugin appears to have allowed it per [this](https://forums.linuxmint.com/viewtopic.php?t=215772) post in 2016 using dconf to set the step from 6 to 2

**Comment by whinis** [comment]
I was looking into updating this with a simple gsetting but it seems I would need to pull-request both this repo as well a cinnamon.desktop in order todo so. Is there a preferred method of doing this ?

**Comment by mtwebster** [comment]
This was addressed here: https://github.com/linuxmint/cinnamon/pull/8884#issuecomment-553994539

**Comment by whinis** [comment]
This is disappointing as 5% is too large and it seems many users are either dealing with much too large a step or compiling their own as I have now done. Having a volume wheel half a turn is 0->100%

**Comment by Loufute** [comment]
Hi @mtwebster,
First, thanks for pointing to that, I was not aware of that discussion, or I would not have asked it here again. Second, I can only but agree with @whinis, the decision arbitrarily taken is not very satisfying to me and it seems to other people.
I understand @clefebvre's view on this, but I do think that letting somewhere the possibility to adjust volume step, would be great. It could be outside the options, but in a config file or something that can very easily changed for those who want it (also, it could allow more flexibility, for instance, adding a condition or something, as in my case the ideal step changes depending on my sound output) ; I think that was also the idea of @deskwizard (i.e., not making it available to everyone). It is hardcoded anyhow, so my opinion is that it would not make a huge difference to externalize the step in a config file instead.
But of course, I am no developer, and I see that this has been closed, so I won't insist, although I find it unfortunate.
Thanks for the work done anyway in Mint, and all the best.
Loufute
