### ISSUE TITLE
memory leak cinnamon  process  

### ISSUE THREAD

**Issue by kost757** [linuxmint/cinnamon-settings-daemon#144]
in mint 18.1 ate memory leak process cinnamon. mint 18 cinnamon process consumes 96-128 MB of memory and mint 18.1 consumes from 96mbи to 4 GB 30 Minutes of memory,then the computer stops. http://img.susepaste.org/39178191
http://img.susepaste.org/25882969

System:    Host: asus-pc Kernel: 4.4.0-21-generic x86_64 (64 bit gcc: 5.3.1)
           Desktop: Cinnamon 3.2.6 (Gtk 3.18.9-1ubuntu3.1)
           Distro: Linux Mint 18.1 Serena
Machine:   System: Acer (portable) product: Aspire ES1-531 v: V1.16
           Mobo: Acer model: Aspire ES1-531 v: V1.16
           Bios: Insyde v: V1.16 date: 02/26/2016
CPU:       Dual core Intel Celeron N3060 (-MCP-) cache: 1024 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 6399
           clock speeds: max: 2480 MHz 1: 1251 MHz 2: 945 MHz
Graphics:  Card: Intel Device 22b1 bus-ID: 00:02.0
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@59.97hz
           GLX Renderer: Mesa DRI Intel HD Graphics (Cherryview)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Audio:     Card Intel Device 2284 driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.4.0-21-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: 1000 bus-ID: 01:00.0
           IF: enp1s0 state: down mac: <filter>
           Card-2: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter
           driver: ath9k bus-ID: 02:00.0
           IF: wlp2s0 state: up mac: <filter>
Drives:    HDD Total Size: 500.1GB (19.3% used)
           ID-1: /dev/sda model: TOSHIBA_MQ01ABF0 size: 500.1GB
Partition: ID-1: / size: 20G used: 12G (65%) fs: ext4 dev: /dev/sda2
           ID-2: /boot size: 462M used: 60M (14%) fs: ext2 dev: /dev/sda5
           ID-3: swap-1 size: 4.10GB used: 0.02GB (0%) fs: swap dev: /dev/sda4
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 60.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 214 Uptime: 30 min Memory: 2859.9/3779.7MB
           Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.461) inxi: 2.2.35

**Comment by clefebvre** [comment]
CSD was split in separate plugins. This should make it easier to see which csd process is eating the memory. If it's the keyboard we have an issue open on this already. Otherwise please create a new issue.
