### ISSUE TITLE
Compiling media-keys plugin fails

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/cinnamon-settings-daemon#146]
Please see the relevant buildlog snippet here:
http://pastebin.com/WYZHu01i
I'm building on Archlinux (Manjaro).

**Comment by JosephMcc** [comment]
```
csd-media-keys-manager.c:1751:14: error: ‘C_DESKTOP_MEDIA_KEY_ROTATE_VIDEO_LOCK’ undeclared (first use in this function)
         case C_DESKTOP_MEDIA_KEY_ROTATE_VIDEO_LOCK:
```

Make sure you have a fully up-to-date cinnamon-desktop. You need this commit here: https://github.com/linuxmint/cinnamon-desktop/commit/dbcec7b6188a1abee9fb410e1983065b94f6012e

**Comment by oberon2007** [comment]
Thank you. I was building the whole group of latest cinnamon pkgs in the chroot so didn't have the other new pkgs installed, yet.
