### ISSUE TITLE
cinnamon-settings-daemon not starting

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/cinnamon-settings-daemon#148]
For a very long time, now (+2 years), gtk theme and desktop backgrounds have been failing to adhere to the settings I chose (on one specific machine).

Looking at .xsession-errors just now, I see

```
cinnamon-session[4127]: WARNING: t+0,18822s: Failed to start app: Unable to start application: Failed to execute child process "/usr/lib/cinnamon-settings-daemon/cinnamon-settings-daemon" (No such file or directory)
cinnamon-session[4127]: WARNING: t+0,60313s: Failed to start app: Unable to start application: Failed to execute child process "/var/lib/gnome-welcome-tour" (No such file or directory)
Debug: nmofono::KillSwitch::KillSwitch(const QDBusConnection&) reply.isValid() false reply.value() true reply.error() QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.freedesktop.URfkill was not provided by any .service files") ((null):0, (null))
```

with the top line being the important one.

What may prompt Cinnamon to try to start csd from /usr/lib/cinnamon-settings-daemon/cinnamon-settings-daemon , when

smo@dell-smo:~$ ls -lh /usr/bin/cinnamon-settings-daemon 
lrwxrwxrwx 1 root root 73 Jan 12 01:03 /usr/bin/cinnamon-settings-daemon -> ../lib/x86_64-linux-gnu/cinnamon-settings-daemon/cinnamon-settings-daemon

?

Best regards,

Sune Mølgaard

**Comment by leigh123linux** [comment]
What distro are you using?

https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/debian/cinnamon-settings-daemon.links.in

**Comment by Fjodor42** [comment]
Ubuntu 16.10 with https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly

The problem has been present on this specific user account on this specific machine for 2+ years with no problems on numerous other machines, though, so I suspect that at some point in time, some configuration migration to a new format, or some-such, may have failed, so I'm mainly interested in discovering, what might prompt cinnamon{,-session} to attempt to start csd from that erroneous location.

Best regards,

Sune Mølgaard

**Comment by Fjodor42** [comment]
Any ideas?

**Comment by Fjodor42** [comment]
It turned out that I had the following three files of between 2 and 4 years of age, which I have now removed:

cinnamon-fallback-mount-helper.desktop
cinnamon-settings-daemon.desktop
cinnamon-sound-applet.desktop

in /etc/xdg/autostart

cinnamon-settings-daemon.desktop specified to exec "/usr/lib/cinnamon-settings-daemon/cinnamon-settings-daemon".

I'll leave it up to you to decide whether such files should be removed as obsolete (possibly after asking the user), or if nothing should be done.

In the latter case, please close this issue.
