### ISSUE TITLE
Touchpad - Why is it so difficult to set Two-Finger Tap to Middle Click

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon-settings-daemon#152]
Good morning,

I wanted to state a concern I have for Cinnamon. It is incredibly difficult to configure the touchpad settings so that a two-finger tap emulates a middle click (instead of the default, right click). Using the System Settings and setting two-finger click emulation to middle click does not work. That's even after rebooting.

The easiest workaround is to run synclient at startup and manually set it through the following:
synclient TapButton2=2

I'm curious. I've tried editing my xorg.conf and set the touchpad behaviour I like. Yet, Cinnamon overwrites (or ignores) this setting. That's really frustrating. Looking around, there's a way to turn off the cinnamon-settings-daemon or use dconf-editor to configure cinnamon through the command line. Either way, that's not very appealing to new users, I imagine.

All I'm asking is for some clarification as to why this behaviour exists and why the System Settings cannot correctly set this touchpad behaviour.

- A long time Cinnamon user who's a little disappointed

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
