### ISSUE TITLE
Area screenshot keyboard shortcut problem

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/cinnamon-settings-daemon#182]
```
 * csd version: 3.2.1+serena
 * Distribution: Mint 18.1
 * Hybrid Graphics: Intel 3rd Gen Core processor Graphics Controller bus-ID: 00:02.0 chip-ID: 8086:0166 +  Advanced Micro Devices [AMD/ATI] Seymour [Radeon HD 6400M/7400M Series] with X.Org 1.18.4 drivers: ati,radeon,intel
 * 64 bit
 ```

**Issue**
Pressing keys "Print" or "Shift+Ctrl+Print" produces nothing but an error notification sound.

**Steps to reproduce**
As above.

**Expected behaviour**
Instead they should do as it says in System Settings > Keyboard > Shortcuts:
Take a screenshot of an area or copy it to clipboard.

**Other information**
1) No problem with the other keyboard shortcuts for different screenshot options.
2) Creating a custom shortcut for the command `gnome-screenshot -a` or `gnome-screenshot -ac` has the same result, using the same key combination or a different one.
3) Both commands **work as expected** from the desktop launcher **Screenshot** or any other.
4) Running the command `gnome-screenshot -a` or `gnome-screenshot -ac` from the terminal also **works as expected** - with this warning message only: 
> Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.

**Comment by lucidyan** [comment]
Same issue here. But in my case there a dialog windows missing after area selection
Linux Mint 19
Cinnamon 3.8.8

**Comment by Sadi58** [comment]
I've just checked also and saw that `gnome-screenshot` still has some problems.
So I stick with the much more feature-rich **Shutter** instead.
Full screen: `shutter --full`
Active window: `shutter --active
`Select window: `shutter --window`
Select area: `shutter --select`

**Comment by icarter09** [comment]
@Sadi58  are you still experiencing this issue?

**Comment by Sadi58** [comment]
@icarter09 Thanks but I'm afraid I can't help because I abandoned gnome-screenshot long time ago and my last stop is this great utility: https://github.com/ksnip/ksnip

**Comment by icarter09** [comment]
@Sadi58 no worries and thanks for the update.
