### ISSUE TITLE
Feature request: allow longer 'suspend when inactive' settings

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/cinnamon-settings-daemon#187]
@CottonEaster commented on [Wed May 31 2017](https://github.com/linuxmint/cinnamon-desktop/issues/93)

![image](https://cloud.githubusercontent.com/assets/9998846/26656021/dfebc7c8-464c-11e7-814d-23742c0d4db3.png)

I'd like to be able to set the computer to suspend when inactive - and when on AC power - after two hours. (Why? Well, my computer gets a bit hot after a while, but I don't want it to go into a deep sleep after only one hour . . I note that Windows - or at least Windows 8 - offers a wider range of time options than, at present, does Mint.)

Mint 18.1 x64 Cinnamon (3.2.7).

---

@blackICE19240 commented on [Wed Aug 16 2017](https://github.com/linuxmint/cinnamon-desktop/issues/93#issuecomment-322642536)

If you google around a bit I'm sure it is possible to do this manually just by editing the right text somewhere

**Comment by xavierhd** [comment]
@leigh123linux It seems like this is resolved has of Mint 18.3
![image](https://user-images.githubusercontent.com/5983431/36520015-aec22638-175c-11e8-9d45-6271751eb27e.png)
