### ISSUE TITLE
Brightness settings has no effect

### ISSUE THREAD

**Issue by bronozoj** [linuxmint/cinnamon-settings-daemon#189]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
3.4.2-1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Intel HD 3000 (intel) + AMD Radeon HD 8750M (amdgpu) (Hybrid Graphics Mode)
 * 32 or 64 bit
64-bit
 ```

**Issue**
any changes to brightness does not apply to the laptop screen. However, the system has the capability to change brightness using the /sys/class/backlight interface

**Steps to reproduce**
perhaps a laptop with hybrid graphics (radeon and intel) is required
/sys/class/backlight lists 3 folders ('acpi_video0', 'acpi_video1', 'intel_backlight')

**Expected behaviour**
changes to brightness settings should reflect on the brightness of the laptop screen

**Other information**
upon checking, modifying brightness through acpi_video0 or acpi_video1 changes brightness of the screen.
also, cinnamon brightness settings seem to apply to intel_backlight instead of acpi_video0

**Comment by icarter09** [comment]
@bronozoj are you still experiencing this issue?

**Comment by bronozoj** [comment]
I have solved this problem previously with a solution I have forgotten. I can no longer test this on the device in question as it has already perished. I will close this issue now
