### ISSUE TITLE
Allow natural scrolling for mouse (not only touchpad)

### ISSUE THREAD

**Issue by bittner** [linuxmint/cinnamon-settings-daemon#192]
```
 * Cinnamon version: 3.2.7
 * Distribution: Ubuntu 17.04 Zesty
 * Graphics hardware *and* driver used -- n/a
 * 64 bit
 ```

**Issue**

The _System Settings_ > _Mouse and Touchpad_ dialog should also handle natural scrolling for for mice, not only for touchpoads. When I use a mouse I should be able to use the scroll-wheel as with natural scrolling.

This is somewhat a follow-up on issue #1930 and PR #1940.

**Steps to reproduce**

- On a Cinnamon desktop go to the System Settings (via the Menu / System Settings))
- In the System Settings go to "Mouse and Touchpad"
- Look for a "natural scrolling" or "Reverse scrolling direction" in the "Mouse" tab -- _it's not found_
- Look for a "natural scrolling" or "Reverse scrolling direction" in the "Touchpad" tab -- _it's there and affects only Touchpads, of course_

**Expected behaviour**

The _System Settings_ > _Mouse and Touchpad_ should have a general "Reverse scrolling direction", or also (a separate) one in the _Mouse_ section.

**Comment by vecernik** [comment]
is there a temporary method to enable "natural scrolling" in Cinnamon atm?

**Comment by robertzaccour** [comment]
This is an important feature for sure. It's available for the touchpad. Why not the mouse? Please include this feature.

**Comment by pblanton** [comment]
The temporary workaround doesn't work in Linux Mint 19 Cinnamon 3.8.9.

Why is this crap so persistent with linux? I mean jeez. Enough people asked for natural scrolling, so somebody implemented it; but only for trackpads? How half-assed is that?

**Comment by thomham** [comment]
I second the feature request. When you have to switch back and forth between macOS and Linux, this is really an issue.
The natural scrolling user experience is much closer to the mobile experience.

**Comment by DarwinSurvivor** [comment]
Another issue with the workaround is that it seems to be "per mouse" and cannot be set until the mouse is attached. This is an issue for laptops as the mouse is often not always attached and/or turned on and sometimes different mice are used on a whim.
