### ISSUE TITLE
My cpu is quad-core

### ISSUE THREAD

**Issue by 1968c** [linuxmint/cinnamon-settings-daemon#193]
![bug1](https://raw.githubusercontent.com/1968c/bug_photo_save/master/2017-10-07%2014-11-41%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)
![BUG2](https://raw.githubusercontent.com/1968c/bug_photo_save/master/2017-10-07%2014-13-24%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by JosephMcc** [comment]
According to this https://ark.intel.com/products/75027/Intel-Core-i5-4200H-Processor-3M-Cache-up-to-3_40-GHz your CPU is 2 core and 4 threads. Exactly what is being shown there.
