### ISSUE TITLE
Feature requests: undo and search

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-settings-daemon#206]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu): 3.6.2+sylvia 
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.3
 * Graphics hardware *and* driver used: Not relevant
 * 32 or 64 bit: 64
 ```

**Issue**

It seems to me that `cinnamon-settings startup` should include an undo function and a search function.

Let me illustrate the usefulness of those functions - as follows. Just now, and by accident, I removed mintUpdate from the startup list. There was no undo button to restore it; and because of a lack of a search-for-applications function, and because of the large number of items in the application list, I could not easily restore the entry that way either. Moreover, having added mintUpdate back as a 'custom command', I suspect that the next time I upgrade my OS, I could end up with two startup instances of mintUpdate.

**Steps to reproduce**

Not applicable.

**Expected behaviour**

Well, I think 'undo' and 'search' would be good!

**Other information**

EDIT: It wasn't entirely trivial to find out that, to run MintUpdate at boot *minimised*, was `mintupdate-launcher` needed - and a novice wouldn't be able to figure that out.

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
