### ISSUE TITLE
Cannot add xfce4-clipman to startup applications

### ISSUE THREAD

**Issue by orschiro** [linuxmint/cinnamon-settings-daemon#208]
```
 * cinnamon-settings-daemon 3.6.2+sylvia
 * LM 18.3 main edition
 ```
Screenshot demonstrating the problem: https://i.imgur.com/PwfnPzp.png

xfce4-clipman provides a .desktop file and can be launched from the general menu: https://i.imgur.com/pZzfLHz.png

**Comment by leigh123linux** [comment]
Try using the proper name xfce4-clipman

/usr/bin//usr/bin/xfce4-clipman

**Comment by orschiro** [comment]
@leigh123linux, it doesn't show up. 

My point is that Clipman provides a .desktop file and (I believe) should appear under

Startup Applications > Add > Choose application.

I know that I can add it with a custom command alternatively but that should only be necessary for scripts that don't have a .desktop file.

![image](https://user-images.githubusercontent.com/170947/33594609-db0c7424-d994-11e7-8832-6ad920dc2949.png)

**Comment by leigh123linux** [comment]
The desktop files are only show in xfce and gnome so your issue is invalid

fix the autostart file

```
sudo sed -i -e 's@OnlyShowIn=XFCE;@OnlyShowIn=XFCE;X-Cinnamon;@g' /etc/xdg/autostart/xfce4-clipman-plugin-autostart.desktop
sudo sed -i -e 's@Hidden=true@Hidden=false@g' /etc/xdg/autostart/xfce4-clipman-plugin-autostart.desktop
```

or maybe the desktop file

```
sudo sed -i -e 's@OnlyShowIn=XFCE;GNOME;@OnlyShowIn=XFCE;GNOME;X-Cinnamon;@g' /usr/share/applications/xfce4-clipman.desktop
```

**Comment by orschiro** [comment]
@leigh123linux thank you very much for your help!

I filed a bug upstream: https://bugzilla.xfce.org/show_bug.cgi?id=14058

Hopefully they will implement the changes.
