### ISSUE TITLE
Feature request: increase volume beyond 100% using the keyboard

### ISSUE THREAD

**Issue by orschiro** [linuxmint/cinnamon-settings-daemon#210]
Cinnamon already has the feature to go beyond 100% from the sound settings. 

However, this requires the user to open the sound settings and drag the switch with the mouse. 

I recall Ubuntu has this great feature to `allow louder than 100%` which allows the user to go beyond 100% using this keyboard volume keys. 

Can we provide something similar in Cinnamon?

Thank you!

![image](https://user-images.githubusercontent.com/170947/33891612-c345e268-df56-11e7-978a-129471f1e54d.png)

![image](https://user-images.githubusercontent.com/170947/33891616-c8f1f0e4-df56-11e7-9675-033ea11019f6.png)

**Comment by leigh123linux** [comment]
Setting amplification to 150% in sound settings  enables the keyboard to go higher than 100%.

![screenshot from 2018-10-10 11-34-26](https://user-images.githubusercontent.com/1299302/46730717-a4f1f280-cc80-11e8-9f66-837e230c176e.jpg)
