### ISSUE TITLE
XSettings: Gtk titlebar click settings are not set

### ISSUE THREAD

**Issue by tanderson-google** [linuxmint/cinnamon-settings-daemon#211]
```
 * csd version 3.2.1-3
 * Distribution - Debian Testing
 * Nvidia graphics with proprietary driver
 * amd64 arch
 ```
cinnamon-settings-daemon does not provide these Xsettings:
Gtk/TitlebarDoubleClick
Gtk/TitlebarMiddleClick
Gtk/TitlebarRightClick

The settings should be backed by these gsettings which are already used by cinnamon:
org.cinnamon.desktop.wm.preferences action-double-click-titlebar
org.cinnamon.desktop.wm.preferences action-middle-click-titlebar
org.cinnamon.desktop.wm.preferences action-right-click-titlebar

**Comment by clefebvre** [comment]
https://github.com/linuxmint/cinnamon-settings-daemon/commit/fa55de663cac569099327bd236a3a1dc64aee1e5
