### ISSUE TITLE
hybrid sleep not working on lid close

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/cinnamon-settings-daemon#214]
@maddler commented on [Thu Jan 25 2018](https://github.com/linuxmint/Cinnamon/issues/7228)

```
 * Cinnamon version 3.6.7
 * Distribution - Fedora 27
 * VGA compatible controller: Intel Corporation Device 591b (rev 04)
 * 64 bit
 ```

**Issue**
Hybrid sleep is not working on lid close.

**Steps to reproduce**
Set "sleep" as defailt action in "power" settings
Enab;e hybrid sleep in settings
Close lid
Remove power supply
Reboot

**Expected behaviour**
Previous session should be restored.

**Other information**
After reboot everything is lost.
Hybrid sleep is working fine otherwise (e.g. via Shutdown Menu With Icons Cinnamon Applet)

**Comment by leigh123linux** [comment]
Lid action is controlled by c-s-d

**Comment by maddler** [comment]
to reply to your question in the original issue, yes "systemctl hybrid-sleep" works just fine.
Tried that as well before raising the issue.
I'm pretty sure it was working before, just not fully sure of when that stopped working tho.
Not sure if that can help, that seems to be working fine with Gnome-desktop 2.32.

Just let me know if there's more I can do.

**Comment by RecNes** [comment]
systemctl hybrid-sleep works fine, but when I close lid of my notebook after disconnecting from AC my session has gone away on reboot.

**Comment by maddler** [comment]
Yes, everything works fine. That's just the close-lid event which appears not to be triggering the hybrid sleep

**Comment by mkresin** [comment]
Hit the same "bug" with Linux Mint 19 Tara. But it rather looks like "not implemented" than a bug.

Following the call chain of the functions, we finally end in [logind_suspend()](https://github.com/linuxmint/cinnamon-settings-daemon/blob/f7c24557526da8f5f022275336a9aef0011ec574/plugins/common/csd-power-helper.c#L50), which calls the logind function `Suspend` via dbus.

According to the [logind documentation](https://www.freedesktop.org/wiki/Software/systemd/logind/), the `HybridSleep` dbus function is what we are interested in. And indeed, after replacing `Suspend` with `HybridSleep` it works as expected.

It boils down to a missing evaluation of xxx and call of Suspend/HybridSleep based on the value.
