### ISSUE TITLE
Suggestion, to do with text sizes, for improving the user experience

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-settings-daemon#216]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu) 3.6.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: N.A.
 * 32 or 64 bit: 64
 ```

**Issue**

The user who is trying to achieve desirable or even just usable text sizes _must look and know to look in multiple places_. _Such a user would be aided by adding a mention_ - and link? - at System Settings - > Fonts -> 'Text scaling factor, to System Settings - > Accessibility -> Large text.

Also: searching for 'scaling' in the Settings search box yields . . nothing. The same goes for the string 'dpi'.

**Comment by leigh123linux** [comment]
Your request has nothing to do with c-s-d.

**Comment by CottonEaster** [comment]
@leigh123linux 
I'm sorry - sometimes I find it hard to know which of Mint's sub-repositories to file things under. Would you please direct me to a more appropriate one? Thank you.

**Comment by leigh123linux** [comment]
System Settings are part of cinnamon.
