### ISSUE TITLE
[Audio] Sound is not redirecting automatically to headphone when jack is connected

### ISSUE THREAD

**Issue by RecNes** [linuxmint/cinnamon-settings-daemon#222]
```
 * csd version: Mint 3.4.4+sonya
 * Distribution: Mint 18.3 Sonya
 * Graphics hardware: 
        VGA compatible controller: Intel Corporation Sky Lake Integrated Graphics
        3D controller: NVIDIA Corporation GM108M [GeForce 940MX]
 * Driver used: Nvidia 384.111-0ubuntu0.16.04.1 (Binary Driver: 384.111)
 * 64 bit
 ```

**Issue**
Sound is not redirecting automatically to headphone when jack is connected

**Steps to reproduce**
Plug in headphone jack and play any media with audio

**Expected behaviour**
Redirect sound to headphone when headphone jack is plugged in

**Other information**
- 00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
- Manually changing connection setting from  Sound Preferences/Output is redirecting sound from speakers to headphone
- Only one input available for audio. Audio and Mic jack input is combined.

**Comment by icarter09** [comment]
csd 4.2.2+tina
Mint 19.2

@RecNes Are you still having this problem? I'm not able to reproduce this issue.

**Comment by RecNes** [comment]
Idk, I switched to MATE a year and half ago.

**Comment by icarter09** [comment]
@RecNes no worries and thanks for the update.
