### ISSUE TITLE
Power settings lid close action doesn't actually inhibit logind

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/cinnamon-settings-daemon#233]
```
 * csd version 3.8.4-1
 * Distribution - Arch
 * Graphics hardware *and* driver used - Intel Haswell-ULT Integrated Graphics Controller i915
 * 64 bit
 ```

**Power settings lid close action doesn't actually inhibit logind**

I have "When the lid is closed - Do nothing" selected for both AC power and battery power.
On closing the lid, the laptop suspends (Default values in `/etc/systemd/logind.conf`)

**Steps to reproduce**

Set "When the lid is closed action" to Do nothing in both cases
Close the laptop lid

**Expected behaviour**
Laptop should not suspend

**Other information**

I could reproduce the same in Mint 19.

**Comment by icarter09** [comment]
csd: 4.2.2+tina
Linux Mint 19.2

I'm not able to reproduce this issue. Performing the steps to reproduce give me the expected behavior. 

@gauravjuvekar are you still experiencing this issue?

**Comment by gauravjuvekar** [comment]
csd: 4.4.0-1
Arch

No repro with this version. 
I have `LidSwitchIgnoreInhibited=no`  in `/etc/systemd/logind.conf`.

My system has changed from the original one on which I reported the bug.
