### ISSUE TITLE
Feature request: power - Add Suspend then Hibernate

### ISSUE THREAD

**Issue by kennethso168** [linuxmint/cinnamon-settings-daemon#237]
```
 * csd version: 3.8.4
 * Distribution: Manjaro
 * Graphics hardware *and* driver used: Intel UHD 620, open source drivers
 * 32 or 64 bit: 64 bit
 ```
Systemd recently merged supported for suspending then hibernate which is a new sleep type that will suspend the system followed by hibernate after a period of time. (More info described in [`systemd-sleep.conf` man page](https://jlk.fjfi.cvut.cz/arch/manpages/man/systemd-sleep.conf.5))

Actually gnome settings daemon (g-s-d) has also integrated suspend-then-hibernate and it is the default action (if available) for suspend in gnome 3.30: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/commit/a6e3ee40d90294c603e1108e19ef8fe8e6af61eb

I have checked with my system with `systemd` version 239.2 and related methods like `CanSuspendThenHibernate` and `SuspendThenHibernate` are available over the logind d-bus interface (`org.freedesktop.login1.Manager`). You can also see the above commit in g-s-d for reference in implementation.

It would really be great if this can be implemented in c-s-d as well. Thank you.

**Comment by miniskipper** [comment]
Currently working on this. Will have to open 3 PRs, though (involves repositories cinnamon, cinnamon-session and cinnamon-settings-daemon).
