### ISSUE TITLE
Sound settings crash with USB sound card

### ISSUE THREAD

**Issue by zrajna** [linuxmint/cinnamon-settings-daemon#239]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu): 3.8.5+tara
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19
 * Graphics hardware *and* driver used: Intel HD 620
 * 32 or 64 bit: 64 bit
 ```

**Issue**

Sound settings crash with USB sound card M-Audio Fast Track Pro selected as sink

**Steps to reproduce**

Open sound settings, select M-Audio Fast Track Pro (Channel A or B) as Device. No issues with pavucontrol though, sink selection works there as expected.
If M-Audio Fast Track Pro device is selected as default (e.g. with pavucontrol), the sound settings window crashes within a second from start.

**Expected behaviour**

Sound settings do not crash, M-Audio Fast Track Pro is selected as device (sink)

**Other information**

```
$ inxi -Ax
Audio:     Card-1 Intel Sunrise Point-LP HD Audio
           driver: snd_hda_intel bus-ID: 00:1f.3
           Card-2 Midiman M-Audio Fast Track Pro
           driver: USB Audio usb-ID: 001-010
           Sound: Advanced Linux Sound Architecture v: k4.15.0-36-generic
 ```

This issue was not present in previous Cinnamon versions (Mint 17-18.3).

I have kept config files in /home from Mint 18.3, and installed Mint 19 on / recently. This update ended up in this issue.

**Comment by leigh123linux** [comment]
Cinnamon provides the sound settings, please file the issue there instead.
Also provide the terminal output for the cinnamon-settings command.
