### ISSUE TITLE
Network Settings Window not displayed correctly

### ISSUE THREAD

**Issue by maj127** [linuxmint/cinnamon-settings-daemon#247]
* Linux Mint 19.1
* Cinnamon 4.0.8
* Kernel 4.15.0-43-generic
* 64 bit
* Display:
*-display
       VGA Adapter:      Intel® HD Graphics 4000
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:27 memory:f0000000-f03fffff memory:e0000000-efffffff ioport:3000(size=64) memory:c0000-dffff
      Resolution: 1366 x 768 (16:9)
 
Issue:
When running Network Settings the displayed window is resized form below in a way that to display the buttons at the bottom of the window you need to either resized it manually or maximized it. 

Steps to reproduce:
1. Right click on Network Manager icon on the bottom panel.
2. Select "Network Settings" from the pop-up menu.

Expected behavior:
The Network Settings window must be displayed with all the controls without the need to resized the window to see them all.

Other information:
Command line to display the Network Settings: /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py network

Screenshot:
![screenshot from 2018-12-26 22-43-57](https://user-images.githubusercontent.com/46169477/50457242-db2b3e00-0962-11e9-96dd-36d258c3c7fb.png)

**Comment by icarter09** [comment]
csd: 4.2.2+tina
Linux Mint 19.2

@maj127 are you still experiencing this issue? I'm not able to reproduce it. The Network Settings window expands to the correct size for me.
