### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon-settings-daemon#248]
```
 * csd version- 4.0.3
 * Distribution - Alt Linux Sisyphus
 * 32 or 64 bit - doesn't matter
 ```

**Issue**
In Alt Linux we have special machine (with large amount of cores) that on regular basis tries to rebuild every existing packages from repository. csd always fails to build on this machine with following error:
```
csd-power-manager.c:50:10: fatal error: csd-power-proxy.h: No such file or directory
 #include "csd-power-proxy.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I believe that it happens because no explicit dependencies are defined between this 2 files (csd-power-manager.c and csd-power-proxy.h).

**Comment by icarter09** [comment]
@vladimir-didenko are you still experiencing this issue?

**Comment by vladimir-didenko** [comment]
@icarter09 I don't have direct access to machine with large core count. So to verify if this issue still persists I will need to update package and wait for 2 weeks until rebuild machine will check build status. But I don't want to do it because I still don't see any dependency defined in Makefile for csd-power-manager.c and csd-power-proxy.h files.

**Comment by icarter09** [comment]
@vladimir-didenko thanks for the update. Since you don't have direct access to that machine and don't see the dependency defined in the Makefile, what do feel are the best steps forward?

**Comment by vladimir-didenko** [comment]
@icarter09 Define explicit dependency between files in Makefile, merge fix into master. I will verify if next release will fail build on multi-core machine or not.

**Comment by leigh123linux** [comment]
Builds fine here with 48 core

```
/usr/bin/make -O -j48 V=1 VERBOSE=1 V=1
```

https://kojipkgs.fedoraproject.org//packages/cinnamon-settings-daemon/4.4.0/1.fc32/data/logs/x86_64/build.log

**Comment by vladimir-didenko** [comment]
> Builds fine here with 48 core

Sorry but it doesn't mean that there is no issue. It only means that this problem could be reproduced only under specific conditions like specific HW, specific timings etc. Error from the issue description is copy-paste from a real build log. So it happens.

**Comment by mkg20001** [comment]
While making https://github.com/NixOS/nixpkgs/pull/78144 the issue occured sporadically

The problem is that even when the jobs in the makefile are added in order, unless there are dependencies, due too the way parallel execution works no guarantees are given that X will be there even though Y executes after it, since from make's perspective there's nothing stopping both from starting at exactly the same time.

This can happen with even 2 cores, it's luck-based. Just let `while make clean && make; do true; done` run and be patient.

**Comment by worldofpeace** [comment]
I'd just invest into https://github.com/linuxmint/cinnamon-settings-daemon/pull/278 :smile: 
Enjoy ninja making things right for everyone.

**Comment by filakhtov** [comment]
@vladimir-didenko you are missing `gdbus-codegen`, look at the rules it is generated with: https://github.com/linuxmint/cinnamon-settings-daemon/blob/717d50d58c6bb8c1d3c3d0e88726795788c47076/plugins/power/Makefile.am#L17-L23

**Comment by vladimir-didenko** [comment]
@filakhtov No gdbus-codegen is definitely installed into build environment.

**Comment by filakhtov** [comment]
@vladimir-didenko okay, if you are to generate this file manually by running `make csd-power-proxy.h` from the `cinnamon-settings-daemon/plugins/power` directory would that work?

**Comment by vladimir-didenko** [comment]
@filakhtov Yes it would work. Non-parallel build works just fine.

**Comment by filakhtov** [comment]
@vladimir-didenko if you please can test now and report back that would be awesome. Thanks in advance!

**Comment by vladimir-didenko** [comment]
@filakhtov Sure. I was able to build package but because problem appeared only on re-build machine I need to check it too. Unfortunately I don't have an ability to force rebuild so I will have results in a week or two. Thank you!
