### ISSUE TITLE
csd-a11y-settings memory leak

### ISSUE THREAD

**Issue by Ghukek** [linuxmint/cinnamon-settings-daemon#250]
```
 * csd version - 4.0.3+tessa
 * Distribution - Mint 19.1 w/ Cinnamon
 * Graphics hardware *and* driver used - NVIDIA Geforce 1060 (laptop) with nvidia-driver-390 version 390.77-0ubuntu0.18.04.1
 * 64 bit
 ```

**Issue**
csd-a11y-settings slowly increases its memory usage, eventually maxing out my RAM and causing performance issues. If I kill the process, it returns.

**Steps to reproduce**
Reboot, or kill the process then it automatically starts again.

**Expected behaviour**
Not 12GiB of memory usage.

**Other information**
I checked previous issues, looks like an issue was opened and closed last year with a similar report but not as much detail. Comment on that one acknowledged a keyboard leak, but this is a settings leak.

**Comment by icarter09** [comment]
@Ghukek  are you still experiencing this issue?

**Comment by Ghukek** [comment]
I was never able to resolve the issue directly. I'm now on Mint 19.2, a newer kernel, a fresh SSD, and am no longer having the issue.
