### ISSUE TITLE
Problem with power management settings

### ISSUE THREAD

**Issue by AveoCross** [linuxmint/cinnamon-settings-daemon#251]
```
 * csd version - 4.03+cindy
 * Distribution - LMDE 3 64bit
  ```
**Issue**
Power settings doesn't work anymore - when i click on "Power Settings" in System Settings nothing appears. And in battery menu i see my battery with "unknown" below. I can set screen brightness without issues and icon is refreshing battery percentage level fine. 

**Expected behaviour**
I should have access to power management settings in system settings panel.

**Other information**
I think that's because i accidentally removed some packages but i don't know what. 
I reinstalled cinnamon-settings-daemon and mint-meta-cinnamon.
When i type "csd-power" i'm getting:
(csd-power:5148): power-plugin-WARNING **: Unable to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(csd-power:5148): power-plugin-WARNING **: IsInhibited failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(csd-power:5148): power-plugin-WARNING **: IsInhibited failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(csd-power:5148): power-plugin-WARNING **: IsInhibited failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

**Comment by AveoCross** [comment]
My friend, which is more linux-savy, did some testing and we're verified that its not a problem with missing packages but with too new packages. Out of the box, after installing LMDE 3 Cindy everything works fine, but after update power settings panel breaks.
Output of cinnamon-settings power:
aveo@aveotp:~$ cinnamon-settings power
True
Using pam module (python3-pampy)
Loading Power module
('/org/freedesktop/UPower/devices/battery_BAT0', 'SANYO', '92P1137', 2, '. GThemedIcon battery-good-symbolic gpm-battery-060 battery-good ', 55.0, 2153990960, 21888, 0)
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 619, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 329, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 133, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 186, in on_module_selected
    self.build_battery_page()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 291, in build_battery_page
    primary_settings.add_row(self.set_device_battery_primary(device))
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 380, in set_device_battery_primary
    details = UPowerGlib.Device.state_to_string(state)
TypeError: Expected a UPowerGlib.DeviceState, but got int

Also - when i remove laptop's battery and run it on charger, settings panel works.

**Comment by smurphos** [comment]
See https://github.com/linuxmint/cinnamon/issues/8285

**Comment by icarter09** [comment]
@AveoCross are you still experiencing this issue? If so, did you check the link that @smurphos provided?

**Comment by AveoCross** [comment]
I totally forgot about that. I don't know honestly. I've moved to classic Linux Mint Cinnamon and everything works perfectly. But it was more less half a year ago. Until i moved issue was present i believe.

**Comment by smurphos** [comment]
@icarter09 - it was fixed and pushed out to LMDE in 4.2

**Comment by stanley3384** [comment]
I have the problem not critical Mint20.3 and others I guess SUSPEND OR POWER DOWN when inactive for 15 minutes works fine for a few day after reboot but after that it does now power down.  It's like that on both my machines.  When it's power down on one I need to hit the power on button the a key to get the logon screen on my other 2nd PC I only need a keyboard touch.
