### ISSUE TITLE
disable touchpad resets itself

### ISSUE THREAD

**Issue by elflng** [linuxmint/cinnamon-settings-daemon#256]
```
 * csd version 4.0.3+tessa
 * Distribution - Mint 19.1 Tessa
 * Graphics hardware Irrelevant
 * 64 bit
 ```

**Issue**

Disabling the touchpad does not work. Once disabled, it will re-enable itself after some time (exact amount not determined).

**Steps to reproduce**
Go to Menu -> Preferences -> Mouse and Touchpad
Click Touchpad
Click Enable touchpad to turn off
Close the preferences window.
Wait a bit (seems to happen at least once an hour but I cannot confirm that exactly), perhaps type and touch the touchpad a few times.
Note that the touchpad is responding again and the preference is back on.

**Expected behaviour**

To stay off when turned off.

**Other information**

This is on a Fujitsu Stylistic TH700, if that is relevant.

**Comment by icarter09** [comment]
csd: 4.2.2+tina
Linux Mint 19.2

So far I haven't been able to reproduce this issue. But will check this off and on to try and verify the expected wait time.
