### ISSUE TITLE
No theme changes after a PR

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon-settings-daemon#264]
```
 * csd version (4.2.2-1)
 * Distribution - (Arch)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**

Hi,

I hope I'm in the right place:)
After a PR, the theme changes are not applied on **cinnamon-spices.linuxmint.com**. 

According to one contributor (claudiux, whom I thank), it would be enough to add a question mark at the end of the download URL.

Would it be possible to make this modification to eliminate this problem?

The link of the discussion: https://github.com/linuxmint/cinnamon-spices-themes/issues/580

Thank you.

**Steps to reproduce**

To each PR

**Comment by leigh123linux** [comment]
This has nothing to do with csd!

**Comment by Bundy01** [comment]
Hi,

could you tell me the right place to post please.
Do you know how to contact the devs at cinnamon-spices.linuxmint.com.

Thank you.
