### ISSUE TITLE
Touch pad no further recognize well between single finger & multi-fingers taping !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-settings-daemon#266]
```
 * csd version: 4.2.2-1.fc30
 * Distribution: Fedora 30
 * Graphics hardware *and* driver used: see "Other information" section bellow.
 * 64 bit
 ```

**Issue**
After upgrade to version 4.2.2 till now, my touch pad did not recognize single-finger from multi-finger tap over touch pad ! Before, it was recognize single finger tap as left-click, while two or more fingers tap as right click. After upgrade to 4.2.2, it deal with all these as left-click !
I saw setting of touchpad & saw that new options added for "click actions" & it set to "automatic". I select "Use multiple fingers for right & middle click" then restart my PC. After restart my touch pad become PARTIALLY respond: I mean it certain times recognize multi-fingers taping as right click but it failed for this on other time when it deal with as single-finger tap !

**Other information**
1) This issue become very sever & absolute on Firefox when I have COMPLETE (not partial) failure to recognize multiple fingers tap as right click. It recognize it always as left click !
2) I tried "emulate mouse buttons" option but it showed complete failure !
3) I tried two finger taping & 3 finger taping & was very very serious that my fingers tap touchpad simultaneously at same time.
4) my system is: Fedora 30 X64 bit Cinnamon edition on Lenovo ThinkPad e550 with Intel core i7 5500 CPU @ 2.40 GH X 2, RAM = 8 GB, HHD = 1 TB, Hybrid VGA (Intel Corporation HD Graphic 5500 + Radeon R7 M265 2GB)

**Comment by icarter09** [comment]
@Nokia808  are you still experiencing this issue?

**Comment by Nokia808** [comment]
@icarter09 
No it is fixed but I forgot to close this bug because I forgot it at all. Sorry.

However, kindly, I suffer from other bug which stand along time & till now not fixed ! - see:
https://github.com/linuxmint/cinnamon-settings-daemon/issues/197#issuecomment-519570758
I saw, just now, you lebal it as "bug". Thank you. I'm ready to help you to fix it .....
