### ISSUE TITLE
System freeze after waking from suspend

### ISSUE THREAD

**Issue by imrock48** [linuxmint/cinnamon-settings-daemon#267]
[crash.tar.gz](https://github.com/linuxmint/cinnamon-settings-daemon/files/3632911/crash.tar.gz)
```
 * csd version : 4.2.2+tina
 * Distribution - Linux Mint 19.2 Tina x86_64 
 * Graphics hardware: AMD Ryzen 5 2500U with integrated Vega 8 GPU with Mesa 19.0.8 and kernel 5.0.0-29-generic
 * 64 bit
 ```

**Issue**
Random system freeze after waking up from suspend mode, have been getting the same issue in other distributions aswell

Pastebin link - https://termbin.com/jknk

**Steps to reproduce**
Suspend and then wake up multiple times, happens randomly like in the 4th try or the 10th try, sometimes the system can go into suspend again and wake normally, sometimes it just freezes and I have to do a hard reboot

**Expected behaviour**
System should wake up normally without freeze

**Other information**
This is the first time I am using a forum like this to report an issue, I just went in the system report app and it helped me reach here, let me know if I did anything wrong. Also the kernel is from official Mint repos and I haven't added any kernel boot parameters, its a fairly recent install of this distribution.

**Comment by icarter09** [comment]
@imrock48  are you still experiencing this issue?

**Comment by imrock48** [comment]
@icarter09 No, issue does not repeat if I wake up from suspend and wait a few seconds before entering any input, I'll close the thread now as issue resolved
