### ISSUE TITLE
cannot select progressive vs interlaced modes

### ISSUE THREAD

**Issue by real-or-random** [linuxmint/cinnamon-settings-daemon#269]
```
 * csd 4.4.2
 * Arch Linux
 ```

**Issue**
The display settings show just one 1920x1080 mode but xrandr gives me 1920x1080 and 1920x1080i.  When I select the one offered in the display settings, I get the interlaced mode, i.e., 1080i. This gives me very weird results on a recent Dell monitor that then turns overscan and deinterlacing on... 

**Expected behaviour**
csd should recognize interlaced modes. Or is this just a bug in the UI/control center?

**Other information**
(After setting the mode on the command line correctly), xrand gives me:
```
HDMI2 connected primary 1920x1080+0+1080 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     30.00 +  25.00    24.00    29.97    23.98
   1920x1200     59.95
   1920x1080     60.00*   50.00    59.94    24.00    23.98
   1920x1080i    60.00    50.00    59.94
   1600x1200     60.00
   1680x1050     59.88
   1280x1024     75.02    60.02
   1280x800      59.91
   1152x864      75.00
   1280x720      60.00    50.00    59.94
   1024x768      75.03    60.00
   800x600       75.00    60.32
   720x576       50.00
   720x576i      50.00
   720x480       60.00    59.94
   720x480i      60.00    59.94
   640x480       75.00    60.00    59.94
   720x400       70.08
```

**Comment by icarter09** [comment]
@eli-schwartz

**Comment by mtwebster** [comment]
This is fixed in the current release.

https://github.com/linuxmint/cinnamon-control-center/commit/f4c95cf92555f74d2758ef9bbd0a45032ca7b085
