### ISSUE TITLE
Change screen brightness automatically on AC connection/disconnection

### ISSUE THREAD

**Issue by FastZet** [linuxmint/cinnamon-settings-daemon#27]
I keep my laptop's brightness at minimum when I'm not charging it and keep it at 85% when it is being charged. In Ubuntu 11.04 it had this option to set different brightness settings regarding when the laptop is discharging and being charged. Can it be implemented in Cinnamon?

**Comment by sentaidigital** [comment]
Is there an issue for the future power profiles we can reference here?
