### ISSUE TITLE
PID: 1694 (csd-keyboard)

### ISSUE THREAD

**Issue by LinuxPusher** [linuxmint/cinnamon-settings-daemon#293]
System:    Host: linuxpusher Kernel: 4.19.0-9-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 
           Desktop: Cinnamon 4.6.6 wm: muffin dm: LightDM Distro: LMDE 4 Debbie 
           base: Debian 10.2 buster 
Machine:   Type: Desktop Mobo: Micro-Star model: X470 GAMING PLUS (MS-7B79) v: 2.0 
           serial: <filter> UEFI: American Megatrends v: A.90 date: 03/07/2019 
CPU:       Topology: 6-Core model: AMD Ryzen 5 2600 bits: 64 type: MT MCP arch: Zen+ rev: 2 
           L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 81589 
           Speed: 1339 MHz min/max: 1550/3400 MHz Core speeds (MHz): 1: 1335 2: 2626 3: 1377 
           4: 1378 5: 1338 6: 1377 7: 1377 8: 1375 9: 1334 10: 3020 11: 1338 12: 1378 
Graphics:  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] vendor: eVga.com. driver: nvidia 
           v: 418.113 bus ID: 1d:00.0 chip ID: 10de:1c03 
           Display: x11 server: X.Org 1.20.4 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa alternate: nv resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce GTX 1060 6GB/PCIe/SSE2 v: 4.6.0 NVIDIA 418.113 
           direct render: Yes 
Audio:     Device-1: NVIDIA GP106 High Definition Audio vendor: eVga.com. driver: snd_hda_intel 
           v: kernel bus ID: 1d:00.1 chip ID: 10de:10f1 
           Device-2: AMD Family 17h HD Audio vendor: Micro-Star MSI driver: snd_hda_intel 
           v: kernel bus ID: 1f:00.3 chip ID: 1022:1457 
           Sound Server: ALSA v: k4.19.0-9-amd64 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI 
           driver: r8169 v: kernel port: f000 bus ID: 18:00.0 chip ID: 10ec:8168 
           IF: enp24s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 1.82 TiB used: 34.12 GiB (1.8%) 
           ID-1: /dev/sda vendor: Western Digital model: WD2003FZEX-00SRLA0 size: 1.82 TiB 
           speed: 6.0 Gb/s serial: <filter> 
Partition: ID-1: / size: 1.78 TiB used: 34.11 GiB (1.9%) fs: ext4 dev: /dev/sda3 
           ID-2: swap-1 size: 8.20 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 28.2 C mobo: N/A gpu: nvidia temp: 43 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 0% 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //muug.ca/mirror/linuxmint/packages debbie main upstream import backport
           2: deb http: //debian.mirror.rafal.ca/debian/ buster main contrib non-free
           3: deb http: //debian.mirror.rafal.ca/debian/ buster-updates main contrib non-free
           4: deb http: //security.debian.org/ buster/updates main contrib non-free
           5: deb http: //debian.mirror.rafal.ca/debian/ buster-backports main contrib non-free
Info:      Processes: 255 Uptime: 32m Memory: 31.42 GiB used: 1.83 GiB (5.8%) Init: systemd v: 241 
           runlevel: 5 Compilers: gcc: 8.3.0 alt: 8 Client: Unknown python3.7 client inxi: 3.0.32 

**Issue**
===================================================================
 Info                                                              
===================================================================
           PID: 1694 (csd-keyboard)
           UID: 1000 (linuxpusher)
           GID: 1000 (linuxpusher)
        Signal: 5 (TRAP)
     Timestamp: Wed 2020-07-22 08:57:15 EDT (8min ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-keyboard
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-keyboard
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (linuxpusher)
       Boot ID: f38863f97c8c44e4acc8c991a26c3d85
    Machine ID: 2da860379b704a0c9b0dc3da694d3b2d
      Hostname: linuxpusher
       Storage: /var/lib/systemd/coredump/core.csd-keyboard.1000.f38863f97c8c44e4acc8c991a26c3d85.1694.1595422635000000.lz4
       Message: Process 1694 (csd-keyboard) of user 1000 dumped core.
                
                Stack trace of thread 1694:
                #0  0x00007f2fa8220c75 n/a (libglib-2.0.so.0)
                #1  0x00007f2fa82235dc g_log_writer_default (libglib-2.0.so.0)
                #2  0x00007f2fa82218d7 g_log_structured_array (libglib-2.0.so.0)
                #3  0x00007f2fa82222fe g_log_structured_standard (libglib-2.0.so.0)
                #4  0x00007f2fa86c7d6b n/a (libgdk-3.so.0)
                #5  0x00007f2fa86d4bc3 n/a (libgdk-3.so.0)
                #6  0x00007f2fa835711a _XError (libX11.so.6)
                #7  0x00007f2fa8354077 n/a (libX11.so.6)
                #8  0x00007f2fa835411d n/a (libX11.so.6)
                #9  0x00007f2fa8355050 _XReply (libX11.so.6)
                #10 0x00007f2fa833afd5 XGetWindowProperty (libX11.so.6)
                #11 0x00007f2fa86e5134 n/a (libgdk-3.so.0)
                #12 0x00007f2fa86e5e35 n/a (libgdk-3.so.0)
                #13 0x00007f2fa86cf06f n/a (libgdk-3.so.0)
                #14 0x00007f2fa86cf356 n/a (libgdk-3.so.0)
                #15 0x00007f2fa8699940 gdk_display_get_event (libgdk-3.so.0)
                #16 0x00007f2fa86cf102 n/a (libgdk-3.so.0)
                #17 0x00007f2fa821af2e g_main_context_dispatch (libglib-2.0.so.0)
                #18 0x00007f2fa821b1c8 n/a (libglib-2.0.so.0)
                #19 0x00007f2fa821b4c2 g_main_loop_run (libglib-2.0.so.0)
                #20 0x00007f2fa899bb15 gtk_main (libgtk-3.so.0)
                #21 0x000055b032d2bae6 main (csd-keyboard)
                #22 0x00007f2fa801209b __libc_start_main (libc.so.6)
                #23 0x000055b032d2bc4a _start (csd-keyboard)
                
                Stack trace of thread 1707:
                #0  0x00007f2fa80dc819 __poll (libc.so.6)
                #1  0x00007f2fa821b136 n/a (libglib-2.0.so.0)
                #2  0x00007f2fa821b25c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f2fa821b2a1 n/a (libglib-2.0.so.0)
                #4  0x00007f2fa8243415 n/a (libglib-2.0.so.0)
                #5  0x00007f2fa7270fa3 start_thread (libpthread.so.0)
                #6  0x00007f2fa80e74cf __clone (libc.so.6)
                
                Stack trace of thread 1708:
                #0  0x00007f2fa80dc819 __poll (libc.so.6)
                #1  0x00007f2fa821b136 n/a (libglib-2.0.so.0)
                #2  0x00007f2fa821b4c2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f2fa85ad266 n/a (libgio-2.0.so.0)
                #4  0x00007f2fa8243415 n/a (libglib-2.0.so.0)
                #5  0x00007f2fa7270fa3 start_thread (libpthread.so.0)
                #6  0x00007f2fa80e74cf __clone (libc.so.6)
                
                Stack trace of thread 1768:
                #0  0x00007f2fa80dc819 __poll (libc.so.6)
                #1  0x00007f2fa821b136 n/a (libglib-2.0.so.0)
                #2  0x00007f2fa821b25c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f2fa27d5ffd n/a (libdconfsettings.so)
                #4  0x00007f2fa8243415 n/a (libglib-2.0.so.0)
                #5  0x00007f2fa7270fa3 start_thread (libpthread.so.0)
                #6  0x00007f2fa80e74cf __clone (libc.so.6)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1694]
[New LWP 1707]
[New LWP 1708]
[New LWP 1768]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-keyboard'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f2fa8220c75 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f2fa3bd7a80 (LWP 1694))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1694]
[New LWP 1707]
[New LWP 1708]
[New LWP 1768]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-keyboard'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f2fa8220c75 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f2fa3bd7a80 (LWP 1694))]
#0  0x00007f2fa8220c75 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f2fa82235dc in g_log_writer_default () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2fa82218d7 in g_log_structured_array () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2fa82222fe in g_log_structured_standard () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f2fa86c7d6b in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007f2fa86d4bc3 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007f2fa835711a in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f2fa8354077 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f2fa835411d in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007f2fa8355050 in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007f2fa833afd5 in XGetWindowProperty () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007f2fa86e5134 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007f2fa86e5e35 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007f2fa86cf06f in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#14 0x00007f2fa86cf356 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#15 0x00007f2fa8699940 in gdk_display_get_event () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#16 0x00007f2fa86cf102 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#17 0x00007f2fa821af2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f2fa821b1c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f2fa821b4c2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f2fa899bb15 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x000055b032d2bae6 in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1694]
[New LWP 1707]
[New LWP 1708]
[New LWP 1768]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-keyboard'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f2fa8220c75 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f2fa3bd7a80 (LWP 1694))]

Thread 4 (Thread 0x7f2fa27cb700 (LWP 1768)):
#0  0x00007f2fa80dc819 in poll () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f2fa821b136 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2fa821b25c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2fa27d5ffd in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f2fa8243415 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f2fa7270fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#6  0x00007f2fa80e74cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7f2fa30bb700 (LWP 1708)):
#0  0x00007f2fa80dc819 in poll () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f2fa821b136 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2fa821b4c2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2fa85ad266 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f2fa8243415 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f2fa7270fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#6  0x00007f2fa80e74cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7f2fa38d0700 (LWP 1707)):
#0  0x00007f2fa80dc819 in poll () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f2fa821b136 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2fa821b25c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2fa821b2a1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f2fa8243415 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f2fa7270fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#6  0x00007f2fa80e74cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7f2fa3bd7a80 (LWP 1694)):
#0  0x00007f2fa8220c75 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#1  0x00007f2fa82235dc in g_log_writer_default () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2fa82218d7 in g_log_structured_array () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2fa82222fe in g_log_structured_standard () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f2fa86c7d6b in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#5  0x00007f2fa86d4bc3 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#6  0x00007f2fa835711a in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#7  0x00007f2fa8354077 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#8  0x00007f2fa835411d in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#9  0x00007f2fa8355050 in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#10 0x00007f2fa833afd5 in XGetWindowProperty () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#11 0x00007f2fa86e5134 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#12 0x00007f2fa86e5e35 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#13 0x00007f2fa86cf06f in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#14 0x00007f2fa86cf356 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#15 0x00007f2fa8699940 in gdk_display_get_event () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#16 0x00007f2fa86cf102 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#17 0x00007f2fa821af2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#18 0x00007f2fa821b1c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#19 0x00007f2fa821b4c2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#20 0x00007f2fa899bb15 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#21 0x000055b032d2bae6 in main ()
No symbol table info available.
#0  0x00007f2fa8220c75 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f2fa82235dc in g_log_writer_default () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2fa82218d7 in g_log_structured_array () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2fa82222fe in g_log_structured_standard () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f2fa86c7d6b in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007f2fa86d4bc3 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007f2fa835711a in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f2fa8354077 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f2fa835411d in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007f2fa8355050 in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007f2fa833afd5 in XGetWindowProperty () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007f2fa86e5134 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007f2fa86e5e35 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007f2fa86cf06f in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#14 0x00007f2fa86cf356 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#15 0x00007f2fa8699940 in gdk_display_get_event () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#16 0x00007f2fa86cf102 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#17 0x00007f2fa821af2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f2fa821b1c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f2fa821b4c2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f2fa899bb15 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x000055b032d2bae6 in main ()

**Steps to reproduce**
Unknown

**Expected behaviour**
Unknown appeared in System Reports LMDE 4

**Other information**
My first Bug report in this manner

**Comment by leigh123linux** [comment]
Duplicate od #279
