### ISSUE TITLE
cinnamon stops working after ten minutes of use

### ISSUE THREAD

**Issue by LuanAraujo1100** [linuxmint/cinnamon-settings-daemon#296]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
 Info                                                              
===================================================================
           PID: 1286 (csd-sound)
           UID: 1000 (luan)
           GID: 1000 (luan)
        Signal: 11 (SEGV)
     Timestamp: Tue 2020-08-18 12:12:28 -03 (1min 37s ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-sound
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-sound
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (luan)
       Boot ID: 1347af558cc9495cb80445f0a6f9da2b
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: luan-desktop
       Storage: /var/lib/systemd/coredump/core.csd-sound.1000.1347af558cc9495cb80445f0a6f9da2b.1286.1597763548000000000000.lz4
       Message: Process 1286 (csd-sound) of user 1000 dumped core.
                
                Stack trace of thread 1286:
                #0  0x00007fa22046d048 n/a (libgdk-3.so.0 + 0x70048)
                #1  0x00007fa22046d38b n/a (libgdk-3.so.0 + 0x7038b)
                #2  0x00007fa2204350f4 gdk_display_get_event (libgdk-3.so.0 + 0x380f4)
                #3  0x00007fa22046d0f6 n/a (libgdk-3.so.0 + 0x700f6)
                #4  0x00007fa2200e2fbd g_main_context_dispatch (libglib-2.0.so.0 + 0x51fbd)
                #5  0x00007fa2200e3240 n/a (libglib-2.0.so.0 + 0x52240)
                #6  0x00007fa2200e3533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #7  0x00007fa22075037d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #8  0x000055fae0126ecb main (csd-sound + 0x3ecb)
                #9  0x00007fa21fec60b3 __libc_start_main (libc.so.6 + 0x270b3)
                #10 0x000055fae012702e n/a (csd-sound + 0x402e)
                
                Stack trace of thread 1293:
                #0  0x00007fa21ffb496f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007fa2200e31ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fa2200e32e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007fa2200e3331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007fa22010c931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fa21fdb4609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fa21ffc1103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1360:
                #0  0x00007fa21ffb496f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007fa2200e31ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fa2200e32e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007fa21d1bb99d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007fa22010c931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fa21fdb4609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fa21ffc1103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1294:
                #0  0x00007fa21ffb496f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007fa2200e31ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fa2200e3533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007fa22033aeda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007fa22010c931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fa21fdb4609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fa21ffc1103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1369:
                #0  0x00007fa21ffba70d syscall (libc.so.6 + 0x11b70d)
                #1  0x00007fa2201305a6 g_cond_wait_until (libglib-2.0.so.0 + 0x9f5a6)
                #2  0x00007fa2200b3561 n/a (libglib-2.0.so.0 + 0x22561)
                #3  0x00007fa22010d32a n/a (libglib-2.0.so.0 + 0x7c32a)
                #4  0x00007fa22010c931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fa21fdb4609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fa21ffc1103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1286]
[New LWP 1293]
[New LWP 1360]
[New LWP 1294]
[New LWP 1369]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-sound'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa22046d048 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
[Current thread is 1 (Thread 0x7fa21e843240 (LWP 1286))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1286]
[New LWP 1293]
[New LWP 1360]
[New LWP 1294]
[New LWP 1369]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-sound'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa22046d048 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
[Current thread is 1 (Thread 0x7fa21e843240 (LWP 1286))]
#0  0x00007fa22046d048 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#1  0x00007fa22046d38b in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#2  0x00007fa2204350f4 in gdk_display_get_event () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007fa22046d0f6 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x00007fa2200e2fbd in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fa2200e3240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fa2200e3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fa22075037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x000055fae0126ecb in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1286]
[New LWP 1293]
[New LWP 1360]
[New LWP 1294]
[New LWP 1369]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-sound'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa22046d048 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
[Current thread is 1 (Thread 0x7fa21e843240 (LWP 1286))]

Thread 5 (Thread 0x7fa21c92d700 (LWP 1369)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007fa2201305a6 in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fa2200b3561 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fa22010d32a in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fa22010c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fa21fdb4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140334240814848, 6988538149472015422, 140726306074782, 140726306074783, 140726306074928, 140334240812160, -6937655252492774338, -6937661235837430722}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fa21ffc1103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7fa21da0c700 (LWP 1294)):
#0  0x00007fa21ffb496f in __GI___poll (fds=0x55fae14a7850, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fa2200e31ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fa2200e3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fa22033aeda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007fa22010c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fa21fdb4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140334258505472, 6988538149472015422, 140726306074894, 140726306074895, 140726306075040, 140334258502784, -6937657602376756162, -6937661235837430722}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fa21ffc1103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7fa21d1a8700 (LWP 1360)):
#0  0x00007fa21ffb496f in __GI___poll (fds=0x55fae14a9610, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fa2200e31ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fa2200e32e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fa21d1bb99d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007fa22010c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fa21fdb4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140334249707264, 6988538149472015422, 140726306073966, 140726306073967, 140726306074112, 140334249704576, -6937658476402600898, -6937661235837430722}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fa21ffc1103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7fa21e241700 (LWP 1293)):
#0  0x00007fa21ffb496f in __GI___poll (fds=0x55fae1496680, nfds=2, timeout=4184) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fa2200e31ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fa2200e32e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fa2200e3331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fa22010c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fa21fdb4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140334267111168, 6988538149472015422, 140726306074462, 140726306074463, 140726306074608, 140334267108480, -6937660932587023298, -6937661235837430722}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fa21ffc1103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7fa21e843240 (LWP 1286)):
#0  0x00007fa22046d048 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#1  0x00007fa22046d38b in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#2  0x00007fa2204350f4 in gdk_display_get_event () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#3  0x00007fa22046d0f6 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#4  0x00007fa2200e2fbd in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fa2200e3240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007fa2200e3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007fa22075037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#8  0x000055fae0126ecb in main ()
No symbol table info available.
#0  0x00007fa22046d048 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#1  0x00007fa22046d38b in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#2  0x00007fa2204350f4 in gdk_display_get_event () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007fa22046d0f6 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x00007fa2200e2fbd in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fa2200e3240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fa2200e3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fa22075037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x000055fae0126ecb in main ()

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
The backtrace is useless as you haven't install the debug symbols and you omitted to fill the template details.
