### ISSUE TITLE
Screen Freeze issue

### ISSUE THREAD

**Issue by rkshah-tech** [linuxmint/cinnamon-settings-daemon#301]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by rkshah-tech** [comment]
===================================================================
 Info                                                              
===================================================================
           PID: 1201 (csd-automount)
           UID: 1000 (rahul)
           GID: 1000 (rahul)
        Signal: 11 (SEGV)
     Timestamp: Wed 2020-09-09 14:16:36 IST (1 day 21h ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (rahul)
       Boot ID: 754f2e5685354487a775a384dca88d8a
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: rahul-Inspiron-1440
       Storage: /var/lib/systemd/coredump/core.csd-automount.1000.754f2e5685354487a775a384dca88d8a.1201.1599641196000000000000.lz4
       Message: Process 1201 (csd-automount) of user 1000 dumped core.
                
                Stack trace of thread 1201:
                #0  0x0000561ffe127430 n/a (csd-automount + 0x6430)
                #1  0x00007f2af655aa28 n/a (libglib-2.0.so.0 + 0x52a28)
                #2  0x00007f2af6559e8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #3  0x00007f2af655a240 n/a (libglib-2.0.so.0 + 0x52240)
                #4  0x00007f2af655a533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #5  0x00007f2af6bef37d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #6  0x0000561ffe126947 n/a (csd-automount + 0x5947)
                #7  0x00007f2af62000b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x0000561ffe126aae n/a (csd-automount + 0x5aae)
                
                Stack trace of thread 1211:
                #0  0x00007f2af62ee96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f2af655a1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f2af655a533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f2af67b1eda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007f2af6583931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f2af5a38609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f2af62fb103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1232:
                #0  0x00007f2af62ee96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f2af655a1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f2af655a2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f2af716999d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007f2af6583931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f2af5a38609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f2af62fb103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1208:
                #0  0x00007f2af62ee96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f2af655a1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f2af655a2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f2af655a331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f2af6583931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f2af5a38609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f2af62fb103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1201]
[New LWP 1211]
[New LWP 1232]
[New LWP 1208]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000561ffe127430 in ?? ()
[Current thread is 1 (Thread 0x7f2af5162a80 (LWP 1201))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1201]
[New LWP 1211]
[New LWP 1232]
[New LWP 1208]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000561ffe127430 in ?? ()
[Current thread is 1 (Thread 0x7f2af5162a80 (LWP 1201))]
#0  0x0000561ffe127430 in ?? ()
#1  0x00007f2af655aa28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2af6559e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2af655a240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f2af655a533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f2af6bef37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x0000561ffe126947 in ?? ()
#7  0x00007f2af62000b3 in __libc_start_main (main=0x561ffe126770, argc=1, argv=0x7ffc6a7a2058, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc6a7a2048) at ../csu/libc-start.c:308
#8  0x0000561ffe126aae in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1201]
[New LWP 1211]
[New LWP 1232]
[New LWP 1208]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000561ffe127430 in ?? ()
[Current thread is 1 (Thread 0x7f2af5162a80 (LWP 1201))]

Thread 4 (Thread 0x7f2af4bf1700 (LWP 1208)):
#0  0x00007f2af62ee96f in __GI___poll (fds=0x56200007cbf0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f2af655a1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2af655a2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2af655a331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f2af6583931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f2af5a38609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139822471517952, -3297247856151596163, 140722094873438, 140722094873439, 140722094873584, 139822471515264, 3199873459944059773, 3199871085038826365}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f2af62fb103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f2af3ba6700 (LWP 1232)):
#0  0x00007f2af62ee96f in __GI___poll (fds=0x56200009b200, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f2af655a1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2af655a2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2af716999d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f2af6583931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f2af5a38609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139822454433536, -3297247856151596163, 140722094872942, 140722094872943, 140722094873088, 139822454430848, 3199866908508320637, 3199871085038826365}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f2af62fb103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f2af43f0700 (LWP 1211)):
#0  0x00007f2af62ee96f in __GI___poll (fds=0x56200008d340, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f2af655a1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2af655a533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2af67b1eda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f2af6583931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f2af5a38609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139822463125248, -3297247856151596163, 140722094873870, 140722094873871, 140722094874016, 139822463122560, 3199872366338012029, 3199871085038826365}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f2af62fb103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f2af5162a80 (LWP 1201)):
#0  0x0000561ffe127430 in ?? ()
No symbol table info available.
#1  0x00007f2af655aa28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2af6559e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2af655a240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f2af655a533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f2af6bef37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x0000561ffe126947 in ?? ()
No symbol table info available.
#7  0x00007f2af62000b3 in __libc_start_main (main=0x561ffe126770, argc=1, argv=0x7ffc6a7a2058, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc6a7a2048) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94695406606992, -3297247856151596163, 94695406594688, 140722094874704, 0, 0, 3298049446315193213, 3199876578412884861}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffc6a7a2058}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#8  0x0000561ffe126aae in ?? ()
No symbol table info available.
#0  0x0000561ffe127430 in ?? ()
#1  0x00007f2af655aa28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2af6559e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2af655a240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f2af655a533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f2af6bef37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x0000561ffe126947 in ?? ()
#7  0x00007f2af62000b3 in __libc_start_main (main=0x561ffe126770, argc=1, argv=0x7ffc6a7a2058, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc6a7a2048) at ../csu/libc-start.c:308
#8  0x0000561ffe126aae in ?? ()

**Comment by leigh123linux** [comment]
Next time fill in the template and install the required debug symbols as the backtrace is worthless without them.
