### ISSUE TITLE
Hung in OS booting

### ISSUE THREAD

**Issue by ravikumar-grps** [linuxmint/cinnamon-settings-daemon#317]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
Observing Boot issue (hang) in normal boot consistently.
Note: Submitting the issue details in safe mode.

**Steps to reproduce**
Boot the system

**Expected behaviour**
[crash.tar.gz](https://github.com/linuxmint/cinnamon-settings-daemon/files/5790548/crash.tar.gz)

**Other
[crash.tar.gz](https://github.com/linuxmint/cinnamon-settings-daemon/files/5790538/crash.tar.gz)
 information**

**Comment by leigh123linux** [comment]
Please use the template next time.
