### ISSUE TITLE
Heavy breakage after updating (4.8.3-1 -> 4.8.4-1)

### ISSUE THREAD

**Issue by atiredman** [linuxmint/cinnamon-settings-daemon#322]
```
 * csd version - upgraded cinnamon-settings-daemon (4.8.3-1 -> 4.8.4-1)
 * Distribution - Arch
 * Graphics hardware *and* driver used - GPU: NVIDIA GeForce GTX 1660 Ti Mobile  Driver: nvidia 460.32.03-2
 * 32 or 64 bit - 64 bit
 ```

**Issue**
After my most recent update I noticed heavy breakage, I Timeshifted back to an earlier snapshot and updated each file 1 by 1 until I isolated the package that was causing the breakage. Some of the things that stopped working after upgrading cinnamon-settings-daemon (4.8.3-1 -> 4.8.4-1) include:

- Media keys stopped working (can't change screen brightness, volume ect.)

- The panel disappeared along with most of the applets (they are still there if you hover your mouse over them, just invisible)

- Theming partially reverts to default settings

- No desktop background (it shows my lightdm background instead)

- Many keyboard shortcuts don't work (but not all)

- Tap to click does not work on my touchpad

**Steps to reproduce**

Update cinnamon-settings-daemon (4.8.3-1 -> 4.8.4-1)
Restart computer

**Expected behaviour**

Things work normally

**Other information**
Laptop is a Lenovo Y540

**Comment by clefebvre** [comment]
fixed by https://github.com/linuxmint/cinnamon-settings-daemon/commit/a94d1ac8727e544519012ab2ac97098764cf29a1.
