### ISSUE TITLE
media keys sometimes stop working

### ISSUE THREAD

**Issue by damian101** [linuxmint/cinnamon-settings-daemon#331]
```
 * Cinnamon version 4.0.10-2
 * RebornOS (Arch)
 * Nvidia Quadro P4000 Mobile, nvidia-dkms 430.14-8
 * 64 bit
 ```
The media keys (play, pause, next/previous track) sometimes stop working. After rebooting everything works fine again.

**Comment by DemonTPx** [comment]
I haven't had problems with this issue anymore for some time and am cinnamon 4.8.6. What version are you running, @xhpohanka ?

**Comment by mondalaci** [comment]
Also running Cinnamon 4.8.6 and no issues for months.

**Comment by xhpohanka** [comment]
I'm on up to date Arch linux.

```bash
$ cinnamon --version
Cinnamon 4.8.6
```

My computer is a laptop so maybe it can be caused by attaching and detaching various keyboards?

**Comment by xhpohanka** [comment]
I was just affected again by this strange behavior.

Each press of media key fires this message in `.xsession-errors`

```
** (csd-media-keys:1663): WARNING **: 10:53:45.150: Error calling method GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.smplayer was not provided by any .service files
```

When I start smplayer, then it is correctly controlled by media keys, but after closing it is still the same. Can the issue be in smplayer? Is it possible that it is not unsubscribing from dbus correctly? Even in such case I would expect some robustness in `csd-media-keys` to be able to handle unexpected situations.

**Comment by mhoran** [comment]
I believe this bug may have been inherited from gnome-settings-daemon: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/45. I believe applying this patch should resolve: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/87/diffs.

**Comment by xhpohanka** [comment]
I'm testing csd-media-keys with this patch. So far it seems that my issues are gone. Let's wait few days more...
