### ISSUE TITLE
csd-wacom crash with csd-wacom-device.c:1857:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)

### ISSUE THREAD

**Issue by ThomasCr** [linuxmint/cinnamon-settings-daemon#332]
```
 * csd version = 4.8.5-1
 * Distribution - Ubuntu Cinnamon Remix 21.04
 * Intel Graphics
 * 64 bit
 * Lenovo Yoga 460
 ```

**Issue**

csd-wacom crash with csd-wacom-device.c:1857:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)

**Steps to reproduce**

run csd-wacom from shell or from cinnamon-settings

```
$ csd-wacom

** (csd-wacom:1094339): WARNING **: 18:10:37.070: Could not set the current stylus ID 0x0 for tablet 'Wacom ISDv4 504c', no general pen found

** (csd-wacom:1094339): WARNING **: 18:10:37.074: Automatically mapping tablet to heuristically-found display.

** (csd-wacom:1094339): WARNING **: 18:10:37.074: Automatically mapping tablet to heuristically-found display.

** (csd-wacom:1094339): WARNING **: 18:10:37.079: Could not set the current stylus ID 0x0 for tablet 'Wacom ISDv4 504c', no general pen found
**
ERROR:../plugins/wacom/csd-wacom-device.c:1857:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
Bail out! ERROR:../plugins/wacom/csd-wacom-device.c:1857:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
Abgebrochen (Speicherabzug geschrieben)
```

I already opened a bug report on Launchpad:
https://bugs.launchpad.net/ubuntu/+source/cinnamon-settings-daemon/+bug/1925842

**Comment by ItzSwirlz** [comment]
Looks like it freaks out if it can't find a pen.

**Comment by ThomasCr** [comment]
found this... looks somehow the same?

https://github.com/linuxmint/cinnamon-control-center/issues/250

**Comment by ItzSwirlz** [comment]
Yeah, that's the same issue. Control center just calls CSD which just fails due to no pen.

**Comment by ThomasCr** [comment]
The Tablet has a Pen, but this is a other bug related to my submission:
https://github.com/linuxwacom/wacom-hid-descriptors/issues/144

**Comment by ItzSwirlz** [comment]
Ah ha-I can't really fix that but CSD can handle a crash for it not being found.

I already have a patch ready to PR, I'm just out right now and will commit later tonight. Then if it works I'll patch it in Ubuntu (you met the right guy)

**Comment by ThomasCr** [comment]
Thanks for caring and fixing the issue 👍 

Is there a test package available now, or you will notify me, when it is ready ?

**Comment by ItzSwirlz** [comment]
I can spin one up in a PPA for you, just give me a day or two.
