### ISSUE TITLE
csd-xsettings segfaults on launch

### ISSUE THREAD

**Issue by autofire372** [linuxmint/cinnamon-settings-daemon#380]
```
 * csd version: 5.8.0
 * Distribution: EndeavourOS
 * Graphics hardware *and* driver used: NVIDIA GeForce GTX 1070 Ti w/ driver 530.41.03
 * 32 or 64 bit: 64 bit
 ```

**Issue**
csd-xsettings has begun persistently segfaulting on launch, delaying sign-in and leaving me stuck with Cinnamon's default app and icon themes.

**Steps to reproduce**
1. Have a working, but outdated, Cinnamon DE setup (happened when updating Cinnamon 5.8 to 5.8.1; also when going from 5.6.8 to 5.8)
2. Update Cinnamon through your distro's package manager (pacman, in my case)
3. Reboot

**Expected behaviour**
I expect to able to change my app and icon themes, and for my system to log in quicker than it currently does.

**Other information**
I obtained the following error message by running a git build of csd-xsettings 5.8.0 in gdb:

`Thread 1 "csd-xsettings" received signal SIGSEGV, Segmentation fault. 
0x00007ffff7516f25 in g_settings_schema_has_key (schema=0x0, key=0x55555556339f "high-contrast") at ../glib/gio/gsettingsschema.c:1063`
`1063      return gvdb_table_has_value (schema->table, key);    `

For completeness, here's the output of `gsettings list-recursively | grep high-contrast`:

`org.cinnamon.desktop.interface high-contrast false`
`org.gnome.desktop.a11y.interface high-contrast false`
`x.dm.slick-greeter high-contrast false`

**Comment by clefebvre** [comment]
Same output here:

```
clem@airtop ~ $ gsettings list-recursively | grep high-contrast
org.cinnamon.desktop.interface high-contrast false
org.gnome.desktop.a11y.interface high-contrast false
x.dm.slick-greeter high-contrast false
```

Which values do you have for these?

**Comment by autofire372** [comment]
> Same output here:
> 
> ```
> clem@airtop ~ $ gsettings list-recursively | grep high-contrast
> org.cinnamon.desktop.interface high-contrast false
> org.gnome.desktop.a11y.interface high-contrast false
> x.dm.slick-greeter high-contrast false
> ```
> 
> Which values do you have for these?

False, on all three.

I also obtained a [gdb backtrace](https://pastebin.com/p7tutsrx).

**Comment by mtwebster** [comment]
Does:
```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```
return any error?

You're on 5.8 on  cinnamon-settings-daemon *and* cinnamon-desktop?

**Comment by autofire372** [comment]
> Does:
> 
> ```
> sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
> ```
> 
> return any error?

No.

> You're on 5.8 on cinnamon-settings-daemon _and_ cinnamon-desktop?

Yes.

**Comment by ihatetheantichrist-1** [comment]
Confirming the bug, it does the same from Victoria repository or compiled from github.
