### ISSUE TITLE
Improve German Translation for "Printing" Notification

### ISSUE THREAD

**Issue by FunProgramer** [linuxmint/cinnamon-settings-daemon#382]
```
 * csd version 5.8.1+victoria
 * Distribution - Mint 21.2
 * NVIDIA GeForce GTX 1050 Ti (driver: nvidia-driver-525)
 * 64 bit
 ```
_System info not important for this issue._
**Issue**
The German title for the "Printing" Notification is "es wird gedruckt".
That looks ugly because it starts with a lowercase letter.

**Steps to reproduce**
Just start a printing job.

**Expected behaviour**
A better translation. I would prefer "Drucken läuft" or something similar.

**Other information**
I know that this is an issue regarding the translation and not the actual code of this project.
But maybe this can be forwarded to some German translator of this project.

I already added a suggestion for this translation in launchpad [here](https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon-settings-daemon/de/246/+translate). (Only visible if you are logged in.)

**Comment by leigh123linux** [comment]
> I already added a suggestion for this translation in launchpad [here](https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon-settings-daemon/de/246/+translate). (Only visible if you are logged in.)
