### ISSUE TITLE
[SGO3]

### ISSUE THREAD

**Issue by flying-foss** [linuxmint/cinnamon-settings-daemon#388]
**Issue**
With the surface in landscape orientation:

When I boot into ubuntu with wayland the login-screen is rotated correctly. But after the login, the image is rotated in portrait mode (and not the landscape mode like it should)

Kernel: 6.6.6-surface-1 (ubuntu with wayland)

Any ideas what's wrong here?

Thanks!

**Comment by mtwebster** [comment]
Hi, this isn't really anything we can help you with - you're better off maybe finding some Ubuntu forum or even chat:

https://ubuntu.com/support/community-support

**Comment by flying-foss** [comment]
sorry i'm wrong here. can i delete the issue?

**Comment by mtwebster** [comment]
I closed them, it's no trouble leaving them like this.

**Comment by flying-foss** [comment]
Thank you!
