### ISSUE TITLE
[SGO3] Touchpad: right click not possible

### ISSUE THREAD

**Issue by flying-foss** [linuxmint/cinnamon-settings-daemon#389]
**Issue**
I can't do a right click with the touchpad after booting. I have to remove the cover and put it onto the surface again- then the touchpad works as expected.

Kernel: 6.6.6-surface-1 (ubuntu with wayland)

Moving the mouse or doing a left click is possible after booting.

Any idea what's wrong here?

Thanks!

**Comment by mtwebster** [comment]
same as #388..
