### ISSUE TITLE
csd-settings-remap - Skipping schema 'org.gnome.settings-daemon.plugins.xsettings' - doesn't exist

### ISSUE THREAD

**Issue by Machion** [linuxmint/cinnamon-settings-daemon#396]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
 * 6.2.0
 * 
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Manjaro Stable
 * 
 * Graphics hardware *and* driver used
 * AMD Radeon 7790 with amdgpu/mesa
 * 
 * 32 or 64 bit
 * 64 bit
 ```
I have two questions: 
1. What das csd-settings-remap exactly do? I couldn't find any docmentation (and not good enough to read the code)? 
2. Why is it in xsession-errors with error mentioned in title?

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-settings-daemon/commit/c5b3e5f85f2370b66a813840b581ee49081ef4e8

For wayland support - we don't have a way to override the settings being used for gtk in a wayland session, so this syncs gnome's settings to ours.

You must not have gnome-settings-daemon package installed. The gnome-power-manager package depends on some of these settings, and is installed by default in Mint/Ubuntu.

It's safe to ignore this warning.

**Comment by Machion** [comment]
I neither have gnome-settings-daemon nor gnome-power-manager installed.
