### ISSUE TITLE
Switch to running on battery not detected while screen lid is closed

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/cinnamon-settings-daemon#40]
If you have your power settings to "do nothing" on lid close running on AC, and "suspend" when running on battery, then unplugging the power with the lid close will not suspend the laptop.

This is a problem because lid close updates appear to be delayed by a couple of seconds at times, so it's quite possible to pull the power, shut the lid, and then the laptop does not suspend. This is bad if you then put it in a bag.

What's needed is probably a new setting to enforce an update to the battery state when the power is pulled while the lid is closed.

**Comment by sentaidigital** [comment]
Maybe we should make Lid Closed a power state.  That way apps will get a power change notification with the right state even if power is removed while the lid is closed.  

Also, the machine shoukd act differently with the lid closed, eithr sleeping or disabling the main display when an external is attached.  To support some KVM switches, the user may need.to force the laptop to stay on even in the absence if a display or keyboard/mouse.

**Comment by sentaidigital** [comment]
Sorry about the poor grammar.  I was commenting from my phone.
