### ISSUE TITLE
Disable touchpad while typing doesn't fully disable the touchpad

### ISSUE THREAD

**Issue by matthew-swift** [linuxmint/cinnamon-settings-daemon#50]
Hi there,

Firstly, I would like to say that LM Qiana is amazing!

I'm not sure if this is a hardware quirk of some sort, but for the record I have a Dell Precision 3800 (business version of Dell XPS 15). I upgraded my laptop the same time I upgraded from LM 16 to 17 so I cannot tell whether this regression is caused by LM or my new laptop!

I have configured the options "Disable touchpad while typing" and "Enable mouseclicks with touchpad". In the latter mode I only need to lightly brush the touchpad for it to register as a mouseclick. Despite disabling the touchpad while typing I end up constantly moving and editing the wrong text due to accidentally touching the touchpad.

It looks like the cinnamon-settings-daemon is launching syndaemon with the -t option:

https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/mouse/csd-mouse-manager.c#L587

Which means, at least for my hardware, that the two modes are incompatible. As a workaround I have deselected the "Enable mouseclicks with touchpad" and now my user experience is much less frustrating. However, I wonder if it would be better to simply not specify the "-t" option to syndaemon? Then I can have my cake and eat it :-)

To test this I killed syndaemon and restarted it manually without the -t option and it worked perfectly.

Matt

**Comment by zfjagann** [comment]
@mtwebster I am using focus-follows-mouse mode and the `-t` completely breaks. I wound up unchecking "Disable Mouse While Typing" and writing my own syndaemon startup application without the `-t` option.

If possible, can we completely remove the `-t` option if focus-follows-mouse is enabled? I'm not opposed to removing it entirley, as @matthew-swift suggests, but it completely breaks the focus-follows-mouse workflow as it is now.

**Comment by rasusmilch** [comment]
I have exactly the same problem on a Lenovo T550. I switched from KDE yesterday and so far am happy. However, typing notes in class causes wild mouse movements. I investigated and found that the appropriate toggle was flipped. If I manually run `syndaemon -k -i 2 -d` WITHOUT `-t` all works as expected. I have disabled the setting in the touchpad area and used the "startup applications" dialog to launch the daemon as a workaround.

This is with default cinnamon desktop install on a Fedora 22 system.

BTW, I never used focus follows mouse, so it would be nice to have a checkbox or something to add/remove the `-t` option.

**Comment by michaelcoyote** [comment]
I'm getting bitten hard on this since my upgrade.  Is there any sort of workaround that could be done aside from killing and restarting `syndaemon` manually?

**Comment by rasusmilch** [comment]
@michaelcoyote What exactly is happening? I setup an autostart of syndaemon and it worked for me. I have since switched back to KDE because of some quirks with cinnamon (though KDE has its issues as well. Gr..)

**Comment by icarter09** [comment]
does anyone have an update on this ticket?

**Comment by mtwebster** [comment]
This should no longer be an issue, but xserver-xorg-input-synaptics should not be installed any more.  xserver-xorg-input-libinput replaces it.
