### ISSUE TITLE
Printer error notification flood

### ISSUE THREAD

**Issue by vranki** [linuxmint/cinnamon-settings-daemon#68]
I have some issue with the network printer, but it's not related to this issue.
I'm getting "Printer error" <printer name> "connecting-to-device" notification about every 10 seconds which is annoying.

CSD should be smarter and not show neverending identical messages. I suppose cups is trying to reconnect every 10s and this failing causes the notification.

Workaround: fix the printer issue or "sudo service cups stop"

**Comment by EricWegscheid** [comment]
I had this same problem. All I had to do was clear the print queue.

**Comment by icarter09** [comment]
@vranki are you still experiencing this issue?

**Comment by vranki** [comment]
Nope, after 6 years it seems to be gone.
