### ISSUE TITLE
Cannot get "High Fidelity" / A2DP mode to stick as default (+ other nuances) - Seeming culprit to my inexperienced eye: /etc/gdm/Xsession[1865]: (cinnamon-settings-daemon:14167): media-keys-plugin-WARNING **: Unable to get default sink

### ISSUE THREAD

**Issue by rhefner** [linuxmint/cinnamon-settings-daemon#69]
Filed the same bug report (at https://bugzilla.redhat.com/show_bug.cgi?id=1164412) and was asked to file an upstream report:

Description of problem:
Using Jabra Revo (bluetooth) Wireless Headphones, I cannot get the "High Fidelity" / A2DP mode to stick as the default.  Actually, the it seems like the cinnamon-settings-daemon is making it where my headset will not even connect by default!  Basically, when I start from a clean slate (steps following), the headset will connect and will reconnect fine, as long as I don't start up the cinnamon-settings-daemon - Once I do, my headset will not connect until I manually select it each time from then on out.

Steps I'm using to get to a clean slate:
- rm -rf ~/.pulse; rm -rf ~/.config/pulse
- sudo systemctl restart bluetooth
- pulseaudio -k (and make sure it respawns)

When I try to connect/reconnect my headset, the following are the defaults in the files under ~/.config/pulse/*default-[sink|source] files:

---
- Clean slate:
  ***********************************************************
  17:31:38 [richard.hefner@RichardHefT440 ~/.config/pulse] # cat 895c007c7a794915a98c4b505f7a1781-default-s*
  alsa_output.pci-0000_00_1b.0.analog-stereo
  alsa_input.pci-0000_00_1b.0.analog-stereo

And I see the following in the logs:
/etc/gdm/Xsession[1865]: (cinnamon-settings-daemon:14167): media-keys-plugin-WARNING **: Unable to get default sink

--- Before powering on my headset, I need to also do a 'power on' in 'bluetoothctl'..?

---
- Initial connection of bluetooth headset:
  ***********************************************************
  17:35:50 [richard.hefner@RichardHefT440 ~] # cat ~/.config/pulse/895c007c7a794915a98c4b505f7a1781-default-s*
  bluez_sink.34_DF_2A_0C_F2_0D
  bluez_source.34_DF_2A_0C_F2_0D

---snip---
kernel: input: 34:DF:2A:0C:F2:0D as /devices/virtual/input/input33
gdm-Xorg-:0[1341]: (II) config/udev: Adding input device 34:DF:2A:0C:F2:0D (/dev/input/event19)
gdm-Xorg-:0[1341]: (**) 34:DF:2A:0C:F2:0D: Applying InputClass "evdev keyboard catchall"
gdm-Xorg-:0[1341]: (**) 34:DF:2A:0C:F2:0D: Applying InputClass "system-keyboard"
gdm-Xorg-:0[1341]: (II) Using input driver 'evdev' for '34:DF:2A:0C:F2:0D'
gdm-Xorg-:0[1341]: (**) 34:DF:2A:0C:F2:0D: always reports core events
gdm-Xorg-:0[1341]: (**) evdev: 34:DF:2A:0C:F2:0D: Device: "/dev/input/event19"
gdm-Xorg-:0[1341]: (--) evdev: 34:DF:2A:0C:F2:0D: Vendor 0 Product 0
gdm-Xorg-:0[1341]: (--) evdev: 34:DF:2A:0C:F2:0D: Found keys
gdm-Xorg-:0[1341]: (II) evdev: 34:DF:2A:0C:F2:0D: Configuring as keyboard
gdm-Xorg-:0[1341]: (**) Option "config_info" "udev:/sys/devices/virtual/input/input33/event19"
gdm-Xorg-:0[1341]: (II) XINPUT: Adding extended input device "34:DF:2A:0C:F2:0D" (type: KEYBOARD, id 17)
gdm-Xorg-:0[1341]: (**) Option "xkb_rules" "evdev"
gdm-Xorg-:0[1341]: (**) Option "xkb_model" "pc104"
gdm-Xorg-:0[1341]: (**) Option "xkb_layout" "us"
---snip---

The only thing here is that the headset is not in A2DP mode and it sounds terrible.  

---
- Disconnect:
  ***********************************************************
  17:36:59 [richard.hefner@RichardHefT440 ~] # cat ~/.config/pulse/895c007c7a794915a98c4b505f7a1781-default-s*
  alsa_output.pci-0000_00_1b.0.analog-stereo
  alsa_input.pci-0000_00_1b.0.analog-stereo

---snip---
/etc/gdm/Xsession[1865]: (cinnamon-settings-daemon:14167): media-keys-plugin-WARNING **: Unable to get default sink
gdm-Xorg-:0[1341]: (II) config/udev: removing device 34:DF:2A:0C:F2:0D
gdm-Xorg-:0[1341]: (II) evdev: 34:DF:2A:0C:F2:0D: Close
gdm-Xorg-:0[1341]: (II) UnloadModule: "evdev"
---snip---

---
- Reconnect:
  ***********************************************************
  17:36:59 [richard.hefner@RichardHefT440 ~] # cat ~/.config/pulse/895c007c7a794915a98c4b505f7a1781-default-s*
  bluez_sink.34_DF_2A_0C_F2_0D
  bluez_source.34_DF_2A_0C_F2_0D

---snip---
/etc/gdm/Xsession[1865]: (cinnamon-settings-daemon:14167): media-keys-plugin-WARNING **: Unable to get default sink
kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
kernel: input: 34:DF:2A:0C:F2:0D as /devices/virtual/input/input35
gdm-Xorg-:0[1341]: (II) config/udev: Adding input device 34:DF:2A:0C:F2:0D (/dev/input/event19)
gdm-Xorg-:0[1341]: (**) 34:DF:2A:0C:F2:0D: Applying InputClass "evdev keyboard catchall"
gdm-Xorg-:0[1341]: (**) 34:DF:2A:0C:F2:0D: Applying InputClass "system-keyboard"
gdm-Xorg-:0[1341]: (II) Using input driver 'evdev' for '34:DF:2A:0C:F2:0D'
gdm-Xorg-:0[1341]: (**) 34:DF:2A:0C:F2:0D: always reports core events
gdm-Xorg-:0[1341]: (**) evdev: 34:DF:2A:0C:F2:0D: Device: "/dev/input/event19"
gdm-Xorg-:0[1341]: (--) evdev: 34:DF:2A:0C:F2:0D: Vendor 0 Product 0
gdm-Xorg-:0[1341]: (--) evdev: 34:DF:2A:0C:F2:0D: Found keys
gdm-Xorg-:0[1341]: (II) evdev: 34:DF:2A:0C:F2:0D: Configuring as keyboard
gdm-Xorg-:0[1341]: (**) Option "config_info" "udev:/sys/devices/virtual/input/input35/event19"
gdm-Xorg-:0[1341]: (II) XINPUT: Adding extended input device "34:DF:2A:0C:F2:0D" (type: KEYBOARD, id 17)
gdm-Xorg-:0[1341]: (**) Option "xkb_rules" "evdev"
gdm-Xorg-:0[1341]: (**) Option "xkb_model" "pc104"
gdm-Xorg-:0[1341]: (**) Option "xkb_layout" "us"
kernel: Bluetooth: hci0 SCO packet for unknown connection handle 257
kernel: Bluetooth: hci0 SCO packet for unknown connection handle 257
kernel: Bluetooth: hci0 SCO packet for unknown connection handle 257
avahi-daemon[902]: Invalid legacy unicast query packet.
kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
---snip---
###### 

Up to this point, I can connect/reconnect my bluetooth headphones and at least SOMETHING will come out of them.  Once I go into the "Sound Settings" using cinnamon, then I cannot reconnect my headphones successfully.

---
- Going into sound settings and selecting my headset
  ***********************************************************
  ---snip---
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 48
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 48
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 48
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  kernel: Bluetooth: hci0 SCO packet for unknown connection handle 0
  ---snip---

---
- Then, once I select A2DP, the following pops up:
  ***********************************************************
  /etc/gdm/Xsession[1865]: (cinnamon-settings-daemon:14167): media-keys-plugin-WARNING **: Unable to get default sink

And, monitoring the pulseaudio default-sink/default-source when I have A2DP enabled on my headset and I get the following:

---snip---
bluez_sink.34_DF_2A_0C_F2_0D
alsa_input.pci-0000_00_1b.0.analog-stereo
---snip---

When I disconnect/reconnect after this point, it stays as the following - No matter what I've done so far!

---snip---
17:43:04 [richard.hefner@RichardHefT440 ~] # cat ~/.config/pulse/895c007c7a794915a98c4b505f7a1781-default-s*
alsa_output.pci-0000_00_1b.0.analog-stereo
alsa_input.pci-0000_00_1b.0.analog-stereo
---snip---

So, I set these as default in /etc/pulseaudio/default.pa, but this seems to have no effect:

---snip---
set-default-sink bluez_sink.34_DF_2A_0C_F2_0D
set-default-source alsa_input.pci-0000_00_1b.0.analog-stereo
---snip---

I didn't have an '/etc/bluetooth/audio.conf' file, but I made one with the following (not sure if this is even used):

---snip---
[General]
Disable=Socket
Disable=Headset
AutoConnect=true
HFP=false

[A2DP]
SBCSources=1
MPEG12Sources=0
---snip---

I loaded the 'module-switch-on-connect' module and disabled 'module-switch-on-port-available' .. I tried with both enabled, that didn't help.

Version-Release number of selected component (if applicable):

17:43:30 [richard.hefner@RichardHefT440 ~/.config/pulse] # rpm -qa | grep cinnamon-settings-daemon
cinnamon-settings-daemon-2.4.3-1.fc21.x86_64

How reproducible:

I can't get it to not reproduce, no matter what I do.  I'm wondering if this is just a configuration issue?  Maybe I'm missing something.

Steps to Reproduce:

See above 

Actual results:

Headset fails to connect in either the low audio quality mode or A2DP.. I have to manually select it each time, then it works until I disconnect and have to reconnect later on.

Expected results:

A2DP should automatically connect once the headset is powered on ... Actually, the headset should automatically switch upon connection but also default to A2DP.

**Comment by thomas-lange-smf** [comment]
Seems like I have the same issues.
Buggy connection to bluetooth headphones.

**Comment by emveeoh** [comment]
I can confirm the same issue. Linux Mint 18 Cinnamon... Bluetooth connects to my headphones. I hear low-quality/degraded audio using the HEADSET HEAD UNIT (HSP/HFP) setting. When I switch to HIGH FIDELITY PLAYBACK (A2DP SINK), the device setting switches back to the internal speakers and the output profile switches back to  HEADSET HEAD UNIT (HSP/HFP). 

I did a re-installation of any package related to bluetooth and pulseaudio and the results remain the same.

**Comment by kybernetik42** [comment]
Same for me for JBL Charge3
HSP/HFP works fine but switching to A2DP don't hear anything. I just made a dist-uprade (Linux Mint 18). Before dist-upgrade the channel switched to internal
Nov 22 21:58:10 Xxxxx kernel: Bluetooth: hci0 SCO packet for unknown connection handle 31

**Comment by taciomedeiros** [comment]
I have this same problem with jbl earbuds and i solve by install 

> sudo apt-get install pulseaudio pulseaudio-module-bluetooth pavucontrol

> pulseaudio -k && pulseaudio --start

**Comment by icarter09** [comment]
@rhefner  are you still experiencing this issue?

**Comment by rhefner** [comment]
@icarter09 I'm not using Cinnamon anymore. If nobody else experienced the issue, it's probably safe to close (~6y old)

**Comment by icarter09** [comment]
@rhefner thanks for the update.
