### ISSUE TITLE
Move notification position configuration from theme to cinnamon-settings

### ISSUE THREAD

**Issue by YamashitaRen** [linuxmint/cinnamon-settings-daemon#96]
Currently you have to configure the notifications position in the theme, like explained here : http://www.bestubuntu.com/how-to-change-notifications-position-in-cinnamon.html

I think it would be better to configure it in the notification module of cinnamon-settings.
Themes should not have to be edited by the end-user.
Since users may want to change the position of their notifications (like me, using a bottom panel configuration, I like to have my notifications at the bottom, near the panel instead of over my titlebar buttons), the configuration should be  easily accessible.

edit : argh I wanted to post this in cinnamon... Hope this is not the wrong place...

**Comment by goetzc** [comment]
Moving the notification position to the bottom would be useful, as it sometimes interferes with some elements, like the web browser tabs or extension.

In previews versions, it was possible to modify the theme's `cinnamon.css` file, under the Notifications section, in `#notification` add or edit the property `margin-from-top-edge-of-screen:` with a pixels value from the screen top to the desired position, like `600px;`

But now with the current Cinnamon 3.0, it seems that this is no longer working. Is there some CSS property to archive this, or some other settings?

**Comment by goetzc** [comment]
I found this issue linuxmint/cinnamon#4892 about the same topic with a [workaround.](https://github.com/linuxmint/Cinnamon/issues/4892#issuecomment-217976720)

**Comment by JosephMcc** [comment]
Duplicate
